### ISSUE TITLE
Run UPDATE statements for 2000's Roundup Lead Form Cancer Diagnosis (2403 records)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#108]
@fedegarza please run this SQL query, and grab the `UPDATE` statements from the last column (**TOTAL 2403 RECORDS**).

```sql
/* APPLIES to Oth as well, as 2000 only sends 'Other Lymphoma Cancer' */
/* Update sets the cancer diagnosis to it's 25 characters limit */
SELECT
    l.id
    , l.date_entered
    , l.first_name
    , l.last_name
    , lead_form_round_up_cancer_diagnosed
    ,
    CASE
        lead_form_round_up_cancer_diagnosed
        WHEN 'Non' THEN 'Non-Hodgkins Lymphoma'
        WHEN 'B-C' THEN 'B-Cell Lymphoma'
        WHEN 'Chr' THEN 'Chronic Lymphocytic Leukemia'
        WHEN 'Chronic Lymphocytic Leuke' THEN 'Chronic Lymphocytic Leukemia'
        WHEN 'Fol' THEN 'Follicular Lymphoma'
        WHEN 'T-C' THEN 'T-Cell Lymphoma'
        WHEN 'Oth' THEN 'Other Lymphoma Cancer'
        WHEN 'No ' THEN 'No Cancer'
        ELSE '*** ERROR ***'
    END AS New_Cancer
    , CONCAT('UPDATE leads SET leads.lead_form_round_up_cancer_diagnosed = "', (SELECT New_Cancer), '" WHERE leads.id = "', l.id, '";') AS UPDATE_QUERY
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
WHERE
    lc.pid_c = '2000'
    AND l.lead_form_product_id = 'c4100f29-210a-342e-a146-5a15ab787997'
    AND (LENGTH(lead_form_round_up_cancer_diagnosed) = 3 OR lead_form_round_up_cancer_diagnosed = "Chronic Lymphocytic Leuke")
    AND lead_form_round_up_cancer_diagnosed NOT IN ('Yes')
ORDER BY
    l.date_entered DESC;
```

**Comment by fedegarza** [comment]
@jesusitd 
I got 2397 lines. do you want to check them out? Let me know

**Comment by jesusitd** [comment]
@fedegarza yes, same as with 3000. The answers are still being truncated.

I'll check it out and will let you know.

**Comment by jesusitd** [comment]
> @fedegarza please run this SQL query, and grab the `UPDATE` statements from the last column (**TOTAL 2403 RECORDS**).
> 
> ```sql
> /* APPLIES to Oth as well, as 2000 only sends 'Other Lymphoma Cancer' */
> /* Update sets the cancer diagnosis to it's 25 characters limit */
> SELECT
>     l.id
>     , l.date_entered
>     , l.first_name
>     , l.last_name
>     , lead_form_round_up_cancer_diagnosed
>     ,
>     CASE
>         lead_form_round_up_cancer_diagnosed
>         WHEN 'Non' THEN 'Non-Hodgkins Lymphoma'
>         WHEN 'B-C' THEN 'B-Cell Lymphoma'
>         WHEN 'Chr' THEN 'Chronic Lymphocytic Leukemia'
>         WHEN 'Chronic Lymphocytic Leuke' THEN 'Chronic Lymphocytic Leukemia'
>         WHEN 'Fol' THEN 'Follicular Lymphoma'
>         WHEN 'T-C' THEN 'T-Cell Lymphoma'
>         WHEN 'Oth' THEN 'Other Lymphoma Cancer'
>         WHEN 'No ' THEN 'No Cancer'
>         ELSE '*** ERROR ***'
>     END AS New_Cancer
>     , CONCAT('UPDATE leads SET leads.lead_form_round_up_cancer_diagnosed = "', (SELECT New_Cancer), '" WHERE leads.id = "', l.id, '";') AS UPDATE_QUERY
> FROM
>     leads l
> LEFT JOIN leads_cstm lc ON
>     l.id = lc.id_c
> WHERE
>     lc.pid_c = '2000'
>     AND l.lead_form_product_id = 'c4100f29-210a-342e-a146-5a15ab787997'
>     AND (LENGTH(lead_form_round_up_cancer_diagnosed) = 3 OR lead_form_round_up_cancer_diagnosed = "Chronic Lymphocytic Leuke")
>     AND lead_form_round_up_cancer_diagnosed NOT IN ('Yes')
> ORDER BY
>     l.date_entered DESC;
> ```

@fedegarza **good to go now with 2403 records. Updates are in the last column of the query above**. Thank you

**Comment by jesusitd** [comment]
@fedegarza :
[2403 records.txt](https://github.com/intakedesk/PowerBI-General/files/3493472/2403.records.txt)

**Comment by fedegarza** [comment]
Done. 2403 rows were updated
