### ISSUE TITLE
Run UPDATE for 3000 Lead Form Cancer Diagnosed to Clean Up Long Names with 25 Chars (1148 Records)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#145]
Query to get the UPDATE statements (1148 lines):
```sql
SELECT
    l.id
    , l.date_entered
    , l.first_name
    , l.last_name
    , lead_form_landing_page
    , lead_form_round_up_cancer_diagnosed
    ,
    CASE
        lead_form_round_up_cancer_diagnosed
        WHEN 'Adult T-cell leukemia lym' THEN 'Adult T-cell leukemia lymphoma'
        WHEN 'Chronic Lymphocytic Leuke' THEN 'Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL)'
        WHEN 'Chronic Lymphocytic Leukemia' THEN 'Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL)'
        WHEN 'Diffuse large B-cell Lymp' THEN 'Diffuse large B-cell Lymphoma (DLBCL)'
        WHEN 'Lymphoblastic lymphoma (W' THEN 'Lymphoblastic lymphoma (Waldenstrom macroglobulinemia)'
        WHEN 'Mantle Cell Lymphoma (MCL' THEN 'Mantle Cell Lymphoma (MCL)'
        WHEN 'Primary central nervous s' THEN 'Primary central nervous system (CNS) Lymphoma'
        ELSE '*** ERROR ***'
    END AS New_Cancer
    , CONCAT('UPDATE leads SET leads.lead_form_round_up_cancer_diagnosed = "', (SELECT New_Cancer), '" WHERE leads.id = "', l.id, '";') AS UPDATE_QUERY
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
WHERE
    lc.pid_c = '3000'
    AND lead_form_product_id = 'c4100f29-210a-342e-a146-5a15ab787997'
    AND lead_form_round_up_cancer_diagnosed IN (
        'Adult T-cell leukemia lym'
        , 'Chronic Lymphocytic Leuke'
        , 'Chronic Lymphocytic Leukemia'
        , 'Diffuse large B-cell Lymp'
        , 'Lymphoblastic lymphoma (W'
        , 'Mantle Cell Lymphoma (MCL'
        , 'Primary central nervous s'
    )
ORDER BY
    l.date_entered DESC;
```

**Comment by jesusitd** [comment]
@fedegarza **please run query above**. It will give you 1038 lines of updates to run in its Last Column

**Comment by fedegarza** [comment]
@jesusitd 
I got 1106 total lines not 1038
Should I run it anyway?

**Comment by jesusitd** [comment]
@fedegarza No.
I just noticed the `lead_form_round_up_cancer_diagnosed` field is still truncating the answers.
![image](https://user-images.githubusercontent.com/50643267/61819993-28508f00-ae22-11e9-910d-4ef83d982ab8.png)

We need to solve it first. But I see the field has 70 characters as agreed. I will figure out what is happening and will let you know.

**Comment by jesusitd** [comment]
> Query to get the UPDATE statements (1148 lines):
> 
> ```sql
> SELECT
>     l.id
>     , l.date_entered
>     , l.first_name
>     , l.last_name
>     , lead_form_landing_page
>     , lead_form_round_up_cancer_diagnosed
>     ,
>     CASE
>         lead_form_round_up_cancer_diagnosed
>         WHEN 'Adult T-cell leukemia lym' THEN 'Adult T-cell leukemia lymphoma'
>         WHEN 'Chronic Lymphocytic Leuke' THEN 'Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL)'
>         WHEN 'Chronic Lymphocytic Leukemia' THEN 'Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL)'
>         WHEN 'Diffuse large B-cell Lymp' THEN 'Diffuse large B-cell Lymphoma (DLBCL)'
>         WHEN 'Lymphoblastic lymphoma (W' THEN 'Lymphoblastic lymphoma (Waldenstrom macroglobulinemia)'
>         WHEN 'Mantle Cell Lymphoma (MCL' THEN 'Mantle Cell Lymphoma (MCL)'
>         WHEN 'Primary central nervous s' THEN 'Primary central nervous system (CNS) Lymphoma'
>         ELSE '*** ERROR ***'
>     END AS New_Cancer
>     , CONCAT('UPDATE leads SET leads.lead_form_round_up_cancer_diagnosed = "', (SELECT New_Cancer), '" WHERE leads.id = "', l.id, '";') AS UPDATE_QUERY
> FROM
>     leads l
> LEFT JOIN leads_cstm lc ON
>     l.id = lc.id_c
> WHERE
>     lc.pid_c = '3000'
>     AND lead_form_product_id = 'c4100f29-210a-342e-a146-5a15ab787997'
>     AND lead_form_round_up_cancer_diagnosed IN (
>         'Adult T-cell leukemia lym'
>         , 'Chronic Lymphocytic Leuke'
>         , 'Chronic Lymphocytic Leukemia'
>         , 'Diffuse large B-cell Lymp'
>         , 'Lymphoblastic lymphoma (W'
>         , 'Mantle Cell Lymphoma (MCL'
>         , 'Primary central nervous s'
>     )
> ORDER BY
>     l.date_entered DESC;
> ```

Hi @fedegarza it should be good to go now, with 1148 UPDATES. I checked and the field is not truncating anymore. Please run it and tell me (**Updates are in last column of this query**).

**Comment by fedegarza** [comment]
Done
