### ISSUE TITLE
Redo: Run UPDATE for 3000's Roundup LF Cancer Other things

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#146]
@fedegarza please run:

FOR OTHER CANCERS AND OTHER LYMPHOMA:
UPDATE PACKAGE 1. Leads with at Least 1 match on Lead Conduit, including Name, and 1 Distinct Answer (1132 Leads)
[RUN.1.-.1132.leads.txt](https://github.com/intakedesk/PowerBI-General/files/3419200/RUN.1.-.1132.leads.txt)

UPDATE PACKAGE 2: Leads Manually matched: 7 Leads. Total 1139 Leads
[RUN.2.-.7.leads.txt](https://github.com/intakedesk/PowerBI-General/files/3419201/RUN.2.-.7.leads.txt)

(Referenced from Issue #96)

**Comment by fedegarza** [comment]
@jesusitd 
Done. 
To next time, please do not include the database name in the query. thanks!
