### ISSUE TITLE
UPDATE 2000 Talcum Diagnosis Date with Lead Conduit's values (1188 Records)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#158]
1199 Leads to Update, BUT 1188 WERE CAUGHT ON LEADCONDUIT:
```sql
SELECT COUNT(*)
FROM leads l LEFT JOIN leads_cstm lc ON l.id = lc.id_c
WHERE l.deleted = 0 AND lc.pid_c = '2000'
    AND lead_form_talcum_powder_cancer_diagnosis_date IN ('2001-01-20', '2001-04-20', '2005-07-20', '2005-08-20', '2019-08-20', '2019-09-20');
```
**TASK MUST BE DONE FOR OTHER PIDs TOO**

**Comment by jesusitd** [comment]
Analysis:
[output-2000-talc-diag-date.xlsx](https://github.com/intakedesk/PowerBI-General/files/3433000/output-2000-talc-diag-date.xlsx)

UPDATE statements (1188):
[talc2000diagDate.txt](https://github.com/intakedesk/PowerBI-General/files/3433007/talc2000diagDate.txt)

Hi @fedegarza can you please run update statements above thank you.

**Comment by fedegarza** [comment]
Done!
