### ISSUE TITLE
FIRMS: Packages Billable should be equal or greater than Zero

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#162]
Fix the formula of Packages Billable everywhere.

Also, the Billable donut below must match what is being shown on the Ad Contract Stats table on top.

Fix:
`Packages Billable = VAR _billable = [Data Migration Sent w Blanks] - [Cases Verified DQ] RETURN IF( _billable >= 0, _billable, 0 )`

**Comment by jesusitd** [comment]
Need to change on every Firm Report, `Packages Billable` for this measure:
```
Packages Billable =
CALCULATE (
    [Cases Count w Blanks],
    FILTER (
        'Cases',
        'Cases'[data_migration_status] = "Sent to Firm"
            && NOT 'Cases'[status] IN { "VerificationQC_DQ", "VerificationQC__Withdrawn" }
    )
)
```

**Comment by jesusitd** [comment]
- DONE Campaigns Master
- DONE Andrus Wagstaff
- DONE Auger Fears
- **PENDING** AWKO
- DONE Bailey Greer
- DONE Bart Bernard
- DONE Canepa
- DONE Caruso
- DONE Christensen
- DONE Citizens
- DONE Dampier
- DONE DBJ
- DONE Dugan
- DONE Entrekin
- DONE FHV Paralegal
- DONE Forman
- DONE Fenner
- DONE Fox Farley
- DONE Fears
- DONE FHV
- DONE GED Lawyers
- DONE Ghia
- DONE Gibson Hill
- DONE Hamilton Gray
- DONE Napoli (regular)

**Comment by jesusitd** [comment]
@CesarITD Please apply this change. Steps are

- Refresh Report
- Change `Packages Billable` measure for the one above
- Notice how the measure value changes the total (it's true!)
- Upload

**Comment by CesarITD** [comment]
All list is done.
