### ISSUE TITLE
HK: Firms Roundup ADD Roundup Details table as in AWKO

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#183]
Cases entity in TV 2.0 for Clients updated.

Need to design and deploy for all firms with a Roundup contract.

TESTING ON AWKO CAMPAIGNS ON ROUNDUP SPECIFIC TAB. WAITING ON HK TO APPROVE DEPLOYMENT.

HK APPROVED DEPLOYMENT ON HIDDEN TABS. FOR EVERYBODY.

For Yoismel: Roundup Details tab on AWKO, copy on every Firm report. **HK: ADD AS A HIDDEN TAB, except for AWKO**

**Comment by jesusitd** [comment]
Done AWKO
Done Andrus Wagstaff
Done Auger

**Comment by yperezitd** [comment]
Completed:
Dampier Campaigns
Dugan Campaigns
Fears N. Campaigns
Ghia Law Campaigns
Gibson Campaigns
Johnston Campaigns
Kogan and DiSalvo Campaigns
Laborde Campaigns
Logue Campaigns
Mass Tort Nexus
Messina Campaings
MHM Campaigns
Michael Stanisci's Campaing
O'Bryan Campaigns
O'Bryan Campaigns - Copy
O'Connor Campaigns
Onder Campaigns
Roden Law Campaigns
Seaton Campaigns
Sheldon Campaigns
