### ISSUE TITLE
UPDATE 2000 Bad.id and fb_ wrong Ad IDs

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#187]
To grab the issue:
```sql
SELECT
    l.id AS 'IntakeDesk ID'
    , l.date_entered AS 'Posting Date (UTC Time)'
    , '' AS 'Posting Date (EST Time)'
    , aos_products.name AS 'Lead  Type'
    , subid_c AS 'Wrong Ad ID'
    , l.first_name AS 'First Name'
    , l.last_name AS 'Last Name'
    , l.phone_home AS 'Phone'
    , LOWER(ea.email_address_caps) AS 'Email Address'
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
INNER JOIN aos_products ON
    l.lead_form_product_id = aos_products.id
    -- AND aos_products.name = 'Roundup Leads'
LEFT JOIN email_addr_bean_rel eb ON
    l.id = eb.bean_id
    AND eb.bean_module = 'Leads'
    AND eb.primary_address = 1
LEFT JOIN email_addresses ea ON
    eb.email_address_id = ea.id
WHERE
    l.deleted = 0
    AND (subid_c LIKE 'fb_%' OR subid_c LIKE '%Bad.id%')
--     AND l.status = 'Duplicate_Dial'
    AND pid_c = '2000'
    AND l.date_entered > '2019-06-03 04:00:00'
ORDER BY
    l.date_entered DESC;
```

**Comment by jesusitd** [comment]
@nmusco Please run this first bunch of Leads to be updated (20 records):
[2000 ad name 1st update 20 records.txt](https://github.com/intakedesk/PowerBI-General/files/3477880/2000.ad.name.1st.update.20.records.txt)

Underlying analysis:
[PID 2000 Leads Last 30D.xlsx](https://github.com/intakedesk/PowerBI-General/files/3477881/PID.2000.Leads.Last.30D.xlsx)

**Comment by jesusitd** [comment]
And the 2nd bunch (17 records): 
[PID 2000 Leads Last 30D - 2nd bunch.xlsx](https://github.com/intakedesk/PowerBI-General/files/3477936/PID.2000.Leads.Last.30D.-.2nd.bunch.xlsx)

[2000 ad name 2nd update 17 records.txt](https://github.com/intakedesk/PowerBI-General/files/3477937/2000.ad.name.2nd.update.17.records.txt)
CC @nmusco

**Comment by nmusco** [comment]
done
