### ISSUE TITLE
FIX: ITD TV 2.0 Date Converted

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#217]
AFFECTING LVA Calendar Latency

**Comment by jesusitd** [comment]
@CesarITD please help me deploying this DAX calculated column to TV 2.0:
`date_converted = VAR _cid = Leads[contact_id] RETURN IF ( LEN ( Leads[contact_id] ) > 0, MINX ( FILTER ( 'Cases', 'Cases'[contact_id] = _cid ), 'Cases'[date_entered] ), BLANK () )`

Format: m/d/yy h:mm tt

**Comment by CesarITD** [comment]
Done and  TV 2.0 is Up.
