### ISSUE TITLE
FIRMS: Bring Roundup Nicotine Usage field into Cases table (ONDER DEMO)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#219]

**Comment by CesarITD** [comment]
Note: In Dataflow no exist a interface to edit SQL Stament.
- Download from "Clients Dataflow" code of Entity "Cases" this code is M Code(powerquery). Open a New PowerBI Desktop to paste the code as New Get data, editor advance I can see in SQL Statement.
- Edit SQL Query to grab new field: `roundup_nicotine_usage`. I can find the name of the field with Inspect in Chrome in the CRM interface. 
Note: In SQL apply transformations to -1 and 1 (No and Yes values).
- Validate the new PowerQuery.
- Copy the PowerQueryCode (with the new column) to the "Client Dataflow".
- Save and Refresh.
- Import New Field into Main Roundup Tab of Fears Reports.
- Look for approval of HK.
- To apply the same for others Reports.

**Comment by CesarITD** [comment]
Change was applied for FEARS and ONDER Firms. Pending approval from HK. This was applied in the Hidden Tab "DEMO FN/MWD - Roundup" and "DEMO Onder - Roundup".

**Comment by jesusitd** [comment]
Deployed to all firms with issue #345
