### ISSUE TITLE
Talc Lead Form analysis Qualif Cancer and CPL analysis

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#264]
Started testing with 3000 Lead Form - Talcum

**Comment by jesusitd** [comment]
Completed:
- DAX Formulas:
Leads Qualified, %
Callable Qualified, %
Projected Conv. (To Convert)

Tab:
- Lead Form Talc: 3 Ads tables.

**Pending:** @CesarITD 
On LF Talc:
- Add Callable 2 to tables below Charts
- Add Callable 2 Card
- Add Callable 2 Filter

- Create CPL Analysis Talcum tab
- Create CPL Analysis Hernia Mesh tab

**Comment by CesarITD** [comment]
3000, 2000 and 6000 done. Pending Lead Vision Ads.

**Comment by CesarITD** [comment]
Hernia Mesh was covered with the Slice option. HK must confirm.

**Comment by CesarITD** [comment]
Reports 2000, 3000, 6000 and "Intake - Lead Vision Ads - All Case Types" were published. Task completed.

**Comment by CesarITD** [comment]
Hernia Mesh was covered with the Slice option. HK must confirm.
