### ISSUE TITLE
PIDs: Add Packages Sent, Signed Pending as in issue 281

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#284]
HK approved deployment of Packages calculations as in issue #281.

To All Applicable tabs.

**Comment by jesusitd** [comment]
LOG:

PID 3000:
- Done Lead Form Roundup
- Done C.A. Roundup
- Done Lead Form Talcum
- Done C.A. Talcum

**Comment by CesarITD** [comment]
New solution applied to obtain the measurements without adding the Documents tables to the model: 
New fields:
Retainer Score

Leads Retainer Pending
Leads Retainer Sent
Leads Retainer Signed

Detail of the solution in the Data Dictionary:

https://intakedesk.sharepoint.com/:x:/s/power-bi-docs/Ec4kvieliCpFlxXl9y_h7KIBQpMuCuJUMYa9YqK9C89PrQ?e=GFnnbp

**Comment by CesarITD** [comment]
Done. The request was to PID's: 2000, 3000, 6000 and 7000.
