### ISSUE TITLE
Generate and agree on a data structure for incoming Ad Spend data from other vendors

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#30]
This must be done prior to start receiving Ad Spend data with 2 main goals:
- Know what data belongs to Which PID
- Define level where Lead Type (product_id) is specified.

Suggestion: make module in CRM to be able to manage this internally, as apparently, this data cannot be automatically pushed into the DB using the same CData connector.

**Comment by jesusitd** [comment]
Proposed structure for incoming Ad Spend and general FB data:

PID Setup must consider:
- Providing one or multiple Accounts exclusively for IntakeDesk. The PID must provide IntakeDesk with the list of Account IDs as part of their PID Setup Procedure.
- Ad Campaigns can only contain Ads for One Tort. This campaign must be duly tagged with the tort name inside brackets **in the CampaignName itself**, for instance: "Something {ivc}", "Some other thing - {taxotere}". The tort name must be standardized so it can be filtered at report level: small caps only, no spaces, provided by IntakeDesk.

**Need to elevate this as part of the PID Setup Procedure**
CC: @nmusco @fedegarza @richarditd

**Comment by jesusitd** [comment]
Proposed standardized tort names for PID Setup Procedure:

{ivc}
{taxotere}
{roundup}
{talcum}
{hernia}
{hip}
{knee}

Other torts must be defined down the road and duly documented in a **PID Setup Standard Operating Procedure (SOP)**

**Comment by jesusitd** [comment]
@fedegarza is setting up Facebook Accounts module to relate FB Accounts to PID. This is a first important step.

**Comment by jesusitd** [comment]
a `LeadVendorAccounts` module was launched in the CRM to match the FB Accounts of the PIDs.

This still does not address the Lead Type issue, as it still does not support Lead Types. On the other side, PID 3000 is still using campaigns to filter by Lead Type, as well as having all his clients mixed inside the same buckets with us, thus needing to Push an 'Intake' string filter. Non-solid solution.

**Comment by nmusco** [comment]
The lead vendor accounts module is not designed to address the issue you are referring, instead you must use the campaigns, ad-sets, or ads modules. Linking a Facebook account to  a specific product is not feasible and will never be done.

**Comment by nmusco** [comment]
As an additional solution, the product_id is now specified on ALL new incoming leads, this should be the correct way to determine which product the lead should be associated with. The product_id field cannot be set by the lead vendor, it is set using a internal process and is always correct.

**Comment by jesusitd** [comment]
CRM Devs made a `Lead Vendor Ad Accounts` module for this.

Issue closed and further requirements will be followed up on new GitHub issues.
