### ISSUE TITLE
Design a DB solution that allows saving changes (log tracking) made to Facebook data.

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#303]

**Comment by CesarITD** [comment]
These  Procedures were created in Database: DEV2.
fb_insert_AdAccounts_log
fb_insert_AdSets_log
fb_insert_Ads_log
fb_insert_Campaigns_log

They need:
- Approval of new Facebook_Sync Update process. To put in Production.
- To put Procedures in Production in the New DB: Facebook_Sync
-  Cron Processes to run every 2 hours.

**Comment by jesusitd** [comment]
@CesarITD @fedegarza I just developed a Python utility that runs from Windows's Task Scheduler.

This utility can be used to fire the Stored Procedures.

https://github.com/intakedesk/py-mysql-stored-procedures

**Comment by jesusitd** [comment]
@CesarITD please adapt SQL stored procedures to act with `FacebookInsights` data, so we can start capturing the data changes.

We'll be needing help from @nmusco / @fedegarza to be able to read from `facebook` DB with Stored Procedures and store the generated data in separate tables, same database, so we may finally close this long-lasting issue requested by HK several times.

**Comment by CesarITD** [comment]
Following Nick suggestion of doing this solution with DB Triggers, I finished testing it in the Facebook_Sync Database in the DEV2 Instance.

Next:
- A DB User was requested to Nick to implement in DEV2/facebook Database.
- To get approval from Nick.
- Deploy to production.

**Comment by jesusitd** [comment]
Hi @CesarITD , any chances we are rolling this out soon to production??? We could use a database in either Slave1 or Slave2 for this, as we need to start storing changes asap.

**Comment by jesusitd** [comment]
Duplicate of #365
