### ISSUE TITLE
New Report: Duplicate Lead and Cases

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#309]
Cases Signed and Deduping Rules.
-	Purpose: To be able to visualize detail of Cases, all in general or to be able to filter them by different criteria. 
-	Filters:
o	Case Creation Date.
o	Case Type (Tort).
o	Match Onder List. An indicator that allows you to mark each case if made match with  the Onder Suppression List.
o	Case Status.
o	PID  (Provider).
o	Contract Name Search Box. This filter allows us to find out which Firms are related in the Title of the Contract.
-	Table with the detail of the cases.

Cases by <Email/Phone/Name> Deduping (three tabs).
-	Purpose: To be able to analyze duplicates in Cases, by Email or Phone or Name and you are  able to filter them by different criteria. 
-	Filters:
o	Case Creation Date.
o	Case Type (Tort).
o	Match Onder List. An indicator that allows you to mark each case if made match with  the Onder Suppression List.
o	Case Status.
o	PID  (Provider).
o	Contract Name Search Box. This filter allows us to find out which Firms are related in the Title of the Contract.
-	Table with the detail of the cases duplicated.

Leads by <Email/Phone/Name> Deduping (three tabs).
-	Purpose: To be able to analyze duplicates in Leads, by Email or Phone or Name and you are  able to filter them by different criteria. 
-	Filters:
o	Leads Entered Date.
o	Lead Type (Tort).
o	Match Onder List. An indicator that allows you to mark each case if made match with  the Onder Suppression List.
-	Table with the detail of the Leads duplicated.

Any comments let us know.

**Comment by jesusitd** [comment]
Scheduled job on 18.209.79.85 VM to run `procedure_dup_tables` SP on slave2.sql.intakedesk.com that generated the Duplicate Leads and Cases by Email and Phone, every hour at minute 45.

Used new Python code on repo https://github.com/intakedesk/py-mysql-stored-procedures.

@CesarITD @fedegarza
