### ISSUE TITLE
Report that allows reconciling / identifying expenses charged on Facebook Business against Credit Card transactions.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#310]

**Comment by CesarITD** [comment]
Eduardo contacted Facebook Support and was told that at the moment they do not give access to this type of financial information. He also indicated that one option is to download the page data manually from Facebook and then compare against credit card transactions.

**Comment by jesusitd** [comment]
Done with Quickbooks payments analysis on `Ad Spend by Provider` report.
