### ISSUE TITLE
Configure CData Sync to Replicate Facebook Business Tables into MySQL

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#311]
Still pending `Campaigns` and `AdSets` TODAY queries due to inefficiency on pulling data from Facebok API.

Documentation on doc-repo:
https://github.com/intakedesk/cdata-sync-facebook

**Comment by CesarITD** [comment]
Last email CData Support:
Neither I nor the development team were able to find a method for supporting an incremental replicate (or server-side filter) on these tables. The requisite fields are simply not exposed by Facebook's API in order for us to support this. The note from the development team is below, please let me know if there are any additional questions!
Unfortunately I am just not seeing any way to do it. In Ads, we use the updated_since parameter:

https://developers.facebook.com/docs/marketing-api/reference/ad-account/ads/

For AdSets and Campaigns, there is no such parameter:

https://developers.facebook.com/docs/marketing-api/reference/ad-account/adsets/
https://developers.facebook.com/docs/marketing-api/reference/ad-account/campaigns/

The date_preset and time_range parameters are ineffective. They only do anything if you are retrieving insights off of the campaigns / ad sets. So as much as we would like to do something here, we can't until Facebook exposes something for us.

Regards,
James Baggs
CData Software Support

**Comment by jesusitd** [comment]
Completed tests (to be documented) with slight, consistent discrepancies.

Sending approval document

**Comment by CesarITD** [comment]
[CData Sync Facebook Integration v03.docx](https://github.com/intakedesk/PowerBI-General/files/3906372/CData.Sync.Facebook.Integration.v03.docx)

**Comment by jesusitd** [comment]
Must move solution to `slave2.sql.intakedesk.com` @CesarITD 

Will we have this ready for switchover?

**Comment by jesusitd** [comment]
@CesarITD It was not clear to me if CData Sync is going to be shut down with the recent servers reduction.

**Comment by jesusitd** [comment]
Deployed into `slave2.sql` and working.

Done.
