### ISSUE TITLE
Leads Scrub Process/Report

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#316]
A solution was developed that allows to reduce the executions times of the Scrub process,

**Comment by CesarITD** [comment]
[Documentation - Lead Scrub Process v04.docx](https://github.com/intakedesk/PowerBI-General/files/3887195/Documentation.-.Lead.Scrub.Process.v04.docx)
Documentation here:
C:\Users\CesarMoncada\Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\

Documentation - Lead Scrub Process v04.docx

**Comment by CesarITD** [comment]
It is pending that Eduardo can to configure the CRON (procedure to get duplicates) that runs every hour. I was giving him problems.

**Comment by jesusitd** [comment]
Let me know if I can assist. I can shoot the command from Python if needed on schedule

**Comment by CesarITD** [comment]
For sure: It is the command that Ed was testing: `mysql -u usuario –ppassword -e 'call procedure_dup_tables();' bi_utilities > sql.output.txt`

**Comment by jesusitd** [comment]
@CesarITD we should get this one back into our todo list? Is this working with refreshes for the Stored procedures?

**Comment by CesarITD** [comment]
No. This is not have a scheduled run. We need push the Cron option. And Ed said me that He received instructions to audit this solution with us.

**Comment by jesusitd** [comment]
Moving to To-do with priority

**Comment by jesusitd** [comment]
CRON feature for de-duplication tables in Slave 2 solved with https://github.com/intakedesk/py-mysql-stored-procedures/

**Comment by jesusitd** [comment]
Done.
