### ISSUE TITLE
UPDATE: 3000's 154 Leads, Web Source to Taboola

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#318]
Original Leads will get updated for SUBID_C and LEAD_FORM_WEB_SOURCE. Notice there are some substitutions for Subid_c, so this document serves as a backup.

This is the processed pre-update list:
[3000 Tarbola Original Leads (change SubiD and Web Source).xlsx](https://github.com/intakedesk/PowerBI-General/files/3769431/3000.Tarbola.Original.Leads.change.SubiD.and.Web.Source.xlsx)

**Comment by jesusitd** [comment]
[sql.txt](https://github.com/intakedesk/PowerBI-General/files/3769505/sql.txt)
(corrected)

Hi @fedegarza can you run this please?

**Comment by fedegarza** [comment]
Done!

**Comment by jesusitd** [comment]
Sorry @fedegarza Rich just told me it's Taboola no Tarbola like i was informed. Can u run it? Gracias sorry
[sql.txt](https://github.com/intakedesk/PowerBI-General/files/3769649/sql.txt)

**Comment by jesusitd** [comment]
Done
