### ISSUE TITLE
Need a list of queries to swap Facebook Name and ID for PID 2000

### ISSUE THREAD

**Issue by nmusco** [intakedesk/PowerBI-General#34]

**Comment by jesusitd** [comment]
Hi Nick, I'm posting the SQL update queries shortly on GitHub
________________________________

**Comment by jesusitd** [comment]
Nick, I was not able to attach the files to GitHub.

Here are the SQL queries to run, plus the SQL queries and Excel file I used to analyze the data.

Run:

  *   query1 (Leads from other sources),
  *   query2 (Leads from FB and no Name duplication issue),
  *   query3 (Leads from FB and duplication issue solved).

How I arrived to results: AnalysisSQL.sql, Analysis Excel.xlsx.

Best regards
________________________________

**Comment by jesusitd** [comment]
[AnalysisExcel.xlsx](https://github.com/intakedesk/PowerBI-General/files/3278414/AnalysisExcel.xlsx)
[AnalysisSQL.txt](https://github.com/intakedesk/PowerBI-General/files/3278417/AnalysisSQL.txt)
[query1.txt](https://github.com/intakedesk/PowerBI-General/files/3278418/query1.txt)
[query2.txt](https://github.com/intakedesk/PowerBI-General/files/3278419/query2.txt)
[query3.txt](https://github.com/intakedesk/PowerBI-General/files/3278420/query3.txt)

**Comment by jesusitd** [comment]
Hi @nmusco can you run these queries to finish updating these set of leads from 2000?

**Comment by jesusitd** [comment]
@nmusco Ran the queries. I checked the list of Leads involved in this issue and they seem to be fixed now after 06-4th. We might be coming back to this to run same queries on previous dates as far back as reasonably possible for PID 2000, so data integrity can be assured across reports ran over other date ranges.

**Comment by jesusitd** [comment]
Now I'm moving to remove Fix code inside Power BI related to this issue.

**Comment by jesusitd** [comment]
Just catched 52 more Leads in this situation, where subid_c still looks like 'fb_%'.

Here are the queries to run. Please @nmusco assist us with this one (UPDATE statements in last column of spreadsheet).
[query 4 undetected Leads.xlsx](https://github.com/intakedesk/PowerBI-General/files/3287634/query.4.undetected.Leads.xlsx)

The query I used:
```sql
/* GET LIST OF POSSIBLY WRONG ADS. SOME FOUND WITH FB_ PREFIX STILL */
SELECT
    subid_c
    , ad.ID AS AdId
    , MIN(date_entered)
    , MAX(date_entered)
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
LEFT JOIN facebook.Ads ad ON
    lc.subid_c = ad.Name
WHERE
    pid_c = '2000'
    AND date_entered >= '2019-06-04 04:00:00'
GROUP BY
    subid_c
    , ad.ID;

/*PREPARATION OF FB_ PREFIXED LEADS FOR TARGET PERIOD*/
SELECT
    l.id AS leadId
    , subid_c
    , ad.ID AS AdId
    , date_entered
    , CONCAT('UPDATE leads_cstm SET leads_cstm.id_c = "', ad.ID, '" WHERE leads_cstm.id_c = "', l.id, '";' ) AS 'UPDATE_QUERY'
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
LEFT JOIN facebook.Ads ad ON
    lc.subid_c = ad.Name
WHERE
    pid_c = '2000'
    AND date_entered >= '2019-06-04 04:00:00'
    AND subid_c LIKE 'fb_%';
```

**Comment by jesusitd** [comment]
@nmusco Please find the queries to run inside this Excel file (last column):
[2000 Leads with fb_ Prefix on Ad ID.xlsx](https://github.com/intakedesk/PowerBI-General/files/3291656/2000.Leads.with.fb_.Prefix.on.Ad.ID.xlsx)

**Updated query to grab Leads (82 count):**
```sql
SELECT
    l.id AS 'Intake Desk Internal ID'
    , l.date_entered AS 'Date Posted'
    , l.first_name AS 'First Name'
    , l.last_name AS 'Last Name'
    , l.phone_home AS 'Phone Number'
    , p.name AS 'Lead Type'
    , lc.subid_c AS 'Wrong Ad ID'
    , ad.ID
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
LEFT JOIN aos_products p ON
    l.lead_form_product_id = p.id
LEFT JOIN (
        SELECT
            ID
            ,
            CASE
                ID
                WHEN '23843508791260073' THEN 'fb_talc_intakedesk_admin_m_a_v2'
                WHEN '23843508791270073' THEN 'fb_talc_intakedesk_2lal_m_b_v2'
                WHEN '23843508791280073' THEN 'fb_talc_intakedesk_2lal_m_a_v2'
                WHEN '23843508791290073' THEN 'fb_talc_intakedesk_admin_m_b_v2'
                ELSE Name
            END AS Name
        FROM
            facebook.Ads
    ) ad ON
    lc.subid_c = ad.Name
WHERE
    pid_c = '2000'
    AND l.date_entered >= '2019-06-04 04:00:00'
    AND subid_c LIKE 'fb%'
ORDER BY
    l.date_entered DESC;

SELECT
    date_entered
    , name
    , case_number
FROM
    cases
WHERE
    date_entered >= '2019-06-14 04:00:00';
```

**Comment by jesusitd** [comment]
Hi @nmusco happy saturday, please don't forget to update the 82 Leads just listed above, the Update queries are in the last column of the spreadsheet

**Comment by nmusco** [comment]
done.
