### ISSUE TITLE
UPDATE Leads from LeadConduit IP Address Issue

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#341]
Generated 2 Lead lists:

- New Dial to get their `date_entered` updated
- Duplicate_Dial to get deleted

Analyzed in this file:
[leadconduitexport - Processed.xlsx](https://github.com/intakedesk/PowerBI-General/files/3859112/leadconduitexport.-.Processed.xlsx)

**Comment by jesusitd** [comment]
@nmusco Hi Nick, can you please run these 2 Update Statements:
[delete sql.txt](https://github.com/intakedesk/PowerBI-General/files/3859124/delete.sql.txt)

[new dial updates.txt](https://github.com/intakedesk/PowerBI-General/files/3859121/new.dial.updates.txt)

**Comment by nmusco** [comment]
Done.
