### ISSUE TITLE
All, Spam: Mark Invalid_Number as Spam in BI Reporting

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#343]
Done 3000

**Comment by jesusitd** [comment]
Updated in TV 2.0

**Comment by CesarITD** [comment]
This was done for PID's: 2000 and 6000. 

Leads Count Root = COUNTA ( Leads[lead_id] )

Leads All Status = 
CALCULATE (
    [Leads Count Root],
    Leads[Is Spam] = "No",
    KEEPFILTERS ( Leads[suspect] <> 1 )
)

Is Spam = 
IF (
    Leads[status] IN { "fake_lead", "invalid", "Invalid_Number" }
        || Leads[suspect] = -1
        || Leads[current_dialer_disposition_c]
        IN { "inval", "Invali", "Invalid", "Fake Lead", "SPAM", "Spam Caller" },
    "Yes",
    "No"
)

Can Jesus close this card or does it have to be done for the rest of the providers?

**Comment by CesarITD** [comment]
Closing because at this moment just 2000, 3000 and 6000 are active.
