### ISSUE TITLE
Clients: Copy ALL hidden Roundup tabs of AWKO into All Firms Reports with Roundup. Keep Hidden.

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#345]
Roundup 2
Roundup 3
Roundup 2nd Diagnosis
...
all tabs

**Comment by jesusitd** [comment]
Calculated Columns to move to SQL:
- Exposure Group 2 (Rename `Roundup Exposure Group 2`, Cesar) **=>SQL**
- Exposure Hours Group 3 Home (Rename `Roundup Exposure Hours Group 3 Home`, Cesar) **=> SQL**
- Exposure Hours Group 3 Work (Rename `Roundup Exposure Hours Group 3 Work`, Cesar) **=> SQL**
- Roundup Cancer 1 Stage Grouped **=> SQL**
- Roundup Cancer Diagnosis 2 Delay Year => **Power Query**
- Roundup Cancer Diagnosis 2 Delay Year Group => **Power Query**
- Roundup Deceased After Diagnosis 2 Delay Months Group **=> SQL**
- Roundup Deceased After Diagnosis 2 Months **=> SQL**
- Roundup Injured Party Deceased w SOL => **Power Query**
- Roundup NHL Age Group **=> SQL**
- Roundup Qualification Confounders **=> Power Query **
- Roundup Treatment 1 Successful Remission (groups) (renamed Label) **=> SQL**
- Roundup Treatment 2 Successful Remission (groups) (renamed Label) **=> SQL**

CC @CesarITD

**Comment by CesarITD** [comment]
**FIXED**
```sql
    CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE            
                WHEN (SELECT roundup_usage_hours_exposure_total) IS NULL THEN NULL
                WHEN (SELECT roundup_usage_hours_exposure_total) <= 40 THEN "40 or less"
                WHEN (SELECT roundup_usage_hours_exposure_total) <= 47 THEN "41-47"
                WHEN (SELECT roundup_usage_hours_exposure_total) <= 72 THEN "48-72"
                WHEN (SELECT roundup_usage_hours_exposure_total) <= 100 THEN "73-100"
                ELSE (SELECT `roundup_usage_exposure_group`)
            END
        ELSE NULL
    END AS `Roundup Exposure Group 2`,
```

**Comment by CesarITD** [comment]
**FIXED**
```sql
    CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE            
                WHEN (SELECT roundup_usage_home_hours_total) IS NULL THEN 'No Home Exp.'
                WHEN (SELECT roundup_usage_home_hours_total) = 0 THEN "No Home Exp."
                WHEN (SELECT roundup_usage_home_hours_total) <= 72 THEN "72 or less"
                WHEN (SELECT roundup_usage_home_hours_total) <= 500 THEN "73-500"
                WHEN (SELECT roundup_usage_home_hours_total) > 500 THEN "500+"
                ELSE 'No Home Exp.'
            END
        ELSE NULL
    END AS `Roundup Exposure Hours Group 3 Home`,
```

**Comment by CesarITD** [comment]
**FIXED**
```SQL
    CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE            
                WHEN (SELECT roundup_usage_work_hours_total) IS NULL THEN 'No Work Exp.'
                WHEN (SELECT roundup_usage_work_hours_total) = 0 THEN "No Work Exp."
                WHEN (SELECT roundup_usage_work_hours_total) <= 72 THEN "72 or less"
                WHEN (SELECT roundup_usage_work_hours_total) <= 500 THEN "73-500"
                WHEN (SELECT roundup_usage_work_hours_total) > 500 THEN "500+"
                ELSE 'No Work Exp.'
            END
        ELSE NULL
    END AS `Roundup Exposure Hours Group 3 Work`,
```

**Comment by CesarITD** [comment]
**FIXED**
```sql
    CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE            
                WHEN (SELECT `Roundup Cancer 1 Stage`) IS NULL THEN NULL
                WHEN (SELECT `Roundup Cancer 1 Stage`) = "Stage 1" THEN "Stages 1-2"
                WHEN (SELECT `Roundup Cancer 1 Stage`) = "Stage 2" THEN "Stages 1-2"
                ELSE (SELECT `Roundup Cancer 1 Stage`)
            END
        ELSE NULL
    END AS `Roundup Cancer 1 Stage Grouped`,
```

**Comment by CesarITD** [comment]
```sql
IF( cases.roundup_diagnosis1_date <>  '' AND cases.roundup_diagnosis2_date >=  cases.roundup_diagnosis1_date AND cases.roundup_injured_party_deceased_date >= cases.roundup_diagnosis2_date  , TIMESTAMPDIFF(MONTH,cases.roundup_diagnosis2_date,cases.roundup_injured_party_deceased_date), null) AS `Roundup Deceased After Diagnosis 2 Months`,
```

**Comment by CesarITD** [comment]
```sql
    CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE            
                WHEN (SELECT `Roundup Deceased After Diagnosis 2 Months`) IS NULL THEN NULL
                WHEN (SELECT `Roundup Deceased After Diagnosis 2 Months`) <= 3 THEN "0-3 mo"
                WHEN (SELECT `Roundup Deceased After Diagnosis 2 Months`) <= 6 THEN "4-6 mo"
                WHEN (SELECT `Roundup Deceased After Diagnosis 2 Months`) <= 12 THEN "6-12 mo"
                ELSE "1+ yrs"
            END
        ELSE NULL
    END AS `Roundup Deceased After Diagnosis 2 Delay Months Group`, 
```

**Comment by jesusitd** [comment]
```SQL
CASE cases_cstm.case_type_c
        WHEN 'Roundup'
        THEN
            CASE
                WHEN (SELECT `Roundup Cancer 1 Age of Diagnosis`) > 0 AND NULLIF((SELECT `roundup_diagnosis1_cancer_type`), '') IS NOT NULL
                THEN CASE WHEN (SELECT `Roundup Cancer 1 Age of Diagnosis`) <= 60 THEN "Clients Under 60" ELSE "Clients Over 60" END
                WHEN (SELECT `Roundup Cancer 2 Age of Diagnosis`) > 0 AND NULLIF((SELECT `roundup_diagnosis2_cancer_type`), '') IS NOT NULL
                THEN CASE WHEN (SELECT `Roundup Cancer 2 Age of Diagnosis`) <= 60 THEN "Clients Under 60" ELSE "Clients Over 60" END
                ELSE NULL
            END
        ELSE NULL
    END AS `Roundup NHL Age Group`,
```

**Comment by jesusitd** [comment]
```sql
CASE
        WHEN cases_cstm.case_type_c = 'Roundup' THEN
            CASE
                WHEN (SELECT `Roundup Treatment 1 Successful Remission`) = "No" THEN "Active Cancer"
                WHEN (SELECT `Roundup Treatment 1 Successful Remission`) = "Yes" THEN "Cancer in Remission"
                ELSE "N/A"
            END
        ELSE NULL
    END AS 'Roundup Treatment 1 Successful Remission Label',
```

**Comment by jesusitd** [comment]
Steps:

IF is Copy of AWKO (assumes it already has all the tabs, except for Campaigns Master):
- Rename Columns as per this issue (see renames above)
- Verify all applicable queries are pointing to Dataflows. If not, restore Dataflows version of Power Query queries
- Refresh Dataset locally. IT WILL FAIL.
- Hit OK in the failure message
- Delete All Calculated Columns regarding this issue (see above again)
- Refresh locally again


IF NOT Copy of AWKO (Most reports actually)
- Refresh Dataset locally
- Copy tabs: Roundup (the original one, Yes), RU Details 1, 2, 3, RU Year of Diagnosis, by grabbing ALL Visuals
- Copy missing Measures AND format measure
- Verify tabs against old report (ideally)
- Upload

IN ALL CASES:
- Verify `Billable` measure
- Ensure in Details Tables that Age of Diagnosis is labeled `Age of Diagnosis 1` and `Age of Diagnosis 2`
- Ensure column formatting is correct
- Ensure in RU Details 3 that the Months are SORTED correctly
- RU Details 3: Verify Filter for NHL Clients Age Group donut (Blank vs. Null)
- RU Details 2: Verify Filter for Deceased After 2nd Diagnosis
- RU Details 2: Verify Filter for 2nd Diagnosis-Years After 1st Diagnosis
- **VERIFY PAGE FILTERS**
- In general **null filters are not working as they as come as empty strings from Dataflows**

**Comment by jesusitd** [comment]
Verifying AWKO:
- RU Details 3 Done (After corrections)
- RU Diagnosis Year (after correction)
- RU Details 2
- RU Details 1
- RU

**OK**. Uploading

**Comment by jesusitd** [comment]
- DONE Campaigns Master
- DONE AWKO
- DONE Andrus Wagstaff
- DONE Auger
- DONE Bart Bernard
- DONE Christensen
- DONE Citizens
- DONE Dampier
- DONE DBJ
- DONE Dugan
- PENDING Fears
- DONE FHV
- DONE FHV Paralegal
- DONE GED Lawyers
- DONE Ghia
- DONE Gibson
- DONE Hamilton
- DONE Johnston
- DONE Kogan
- DONE Laborde
- DONE Logue
- DONE McDonald Worley
- DONE Messina
- DONE MHM
- PENDING MStanisci
- PENDING MTN

**Comment by CesarITD** [comment]
Down - Up
Last ->  Napoli Shkolnik Campaigns - Paralegal.pbix

**Comment by jesusitd** [comment]
- DONE Fears
- DONE M Stanisci
- DONE MTN
- DONE MTN Campaigns
