### ISSUE TITLE
TV 2.0: Fix Ads Model to match LVA Cards vs TV PID Cards accordingly

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#354]
Sample screenshot for Oct-Nov 2019 discrepancy showing 249 leads Blank PID blank Tort

**Comment by CesarITD** [comment]
Fixed in TV 2.0

Query: OthersAds
/* New Ads from Other PIDs than 3000 And Not In facebook.Ads */
/* CMon 2019NOV26 This filter was take out: pid_c <> '3000' to consolidate numbers with TV 3000 */
SELECT
    DISTINCT
    CASE
        WHEN subid_c = 'Inbound' THEN 'Inbound'
        WHEN subid_c = 'stiuswalcvi' THEN 'gs_mti_ivc_lawsuits'
        WHEN subid_c = 'daorbneponegcvi' THEN 'bs_mti_ivc_gen_openbroad'
        WHEN subid_c = 'bnegcvi' THEN 'gs_mti_ivc_genb'
        WHEN subid_c = 'tnemelttescvi' THEN 'gs_mti_ivc_settlement'
        WHEN subid_c = 'enegcvi' THEN 'gs_mti_ivc_gene'
        WHEN subid_c = 'reywalcvi' THEN 'gs_mti_ivc_lawyer'
        WHEN subid_c = 'stiuswalcvi' THEN 'bs_mti_ivc_lawsuits'
        WHEN subid_c = 'sesaccvi' THEN 'gs_mti_ivc_cases'
        WHEN subid_c = 'lrmt003' THEN 'lrmt003'
        WHEN subid_c = '870' THEN '870'
        WHEN subid_c = 'pudnuor' THEN 'gs_mt_roundup'
        WHEN subid_c = 'pudnuor' THEN 'bs_mt_roundup'
        ELSE subid_c
    END AS 'AdId'
    , '' AS 'Target'
    , (SELECT AdId) AS 'Name'
    , '' AS 'AdStatus'
    , CONCAT(pid_c, '-', aos_products.short_name) AS CampaignId
    , aos_products.short_name AS 'Lead Type'
    , CONCAT(aos_products.short_name, '-', (SELECT AdId)) AS 'Lead Type SubId'
    , CONCAT(pid_c, '-', aos_products.short_name, '-', (SELECT AdId)) AS 'Ad Id Complete'
    ,
    CASE
        WHEN LEFT((SELECT AdId), 2) = 'bs' THEN 'Bing'
        WHEN LEFT((SELECT AdId), 2) = 'fb' THEN 'Facebook'
        WHEN LEFT((SELECT AdId), 2) = 'gs' THEN 'Google'
        WHEN (SELECT AdId) = '870' THEN 'Affiliate'
        ELSE 'Other'
    END AS 'Campaign Source'
FROM
    leads
INNER JOIN leads_cstm ON
    leads.id = leads_cstm.id_c
    -- CMon 2019NOV26 AND pid_c <> '3000'
    AND NULLIF(
        pid_c
        , ''
    ) IS NOT NULL
    AND NULLIF(
        subid_c
        , ''
    ) IS NOT NULL
INNER JOIN aos_products ON
    leads.lead_form_product_id = aos_products.id
WHERE
    leads.deleted = 0
    AND leads.date_entered >= '2019-06-04'
    AND subid_c NOT IN (
        SELECT
            ID
        FROM
            facebook.Ads
    ) ;

**Comment by CesarITD** [comment]
Fixed in TV 3000:

Query Leads / RU Qulif Cancer:

    CASE
        WHEN aos_products.short_name = 'Roundup' THEN CASE WHEN leads.lead_form_round_up_cancer_diagnosed NOT IN ( 'Other Cancers', 'Other Lymphoma Cancer', 'No Cancer', 'Oth', 'Other', 'undefined', 'Lung Cancer') THEN 'Yes' ELSE 'No' END
        WHEN aos_products.short_name = 'Talcum' THEN CASE WHEN leads.lead_form_talcum_powder_cancer_type IN ('Ovarian Cancer', 'Fallopian Tube Cancer', 'Invasive Fallopian Tube C', 'Clear Cell Epithelial OVCA', 'Endometroid Epithelial OVCA', 'Serous Epithelial OVCA', 'Invasive/Well-differenciated Mucinous OVCA') THEN 'Yes' ELSE 'No' END
        ELSE "Yes"
    END AS 'Lead Form Qualifying',

This is not yet in Production

**Comment by jesusitd** [comment]
@CesarITD Cesar please design a notification email where we highlight the difference before-after the change

**Comment by CesarITD** [comment]
3000 vs LVA amost done. Just pending CPL Qualif. Card.

**Comment by CesarITD** [comment]
Fixes to 2000:
- Lung Cancer added
    CASE
        WHEN aos_products.short_name = 'Roundup' THEN leads.lead_form_round_up_cancer_diagnosed NOT IN ('Multiple Myeloma', 'Other Lymphoma Cancer', 'No Cancer','Lung Cancer')
        WHEN aos_products.short_name = 'Talcum' THEN leads.lead_form_talcum_powder_cancer_type IN (
            'Ovarian Cancer',
            'Ovarian',
            'Fallopian Tube Cancer',
            'Invasive Fallopian Tube C',
            'Invasive Fallopian Tube Cancer',
            'Clear Cell Epithelial OVCA',
            'Clear Cell Epithelial OVC',
            'Endometroid Epithelial OVCA',
            'Endometroid Epithelial OV',
            'Serous Epithelial OVCA',
            'Invasive/Well-differenciated Mucinous OVCA'
            'Invasive/Well-differencia'
            )
        ELSE TRUE
    END AS 'Lead Form Qualifying',

**Comment by CesarITD** [comment]
Fixes to 2000:

- CPL Reatime changed to CPL 3 Gross per Ad
- All pages filter "Lead Status is not Duplicate_Dial" was take out.


TV 2000 was loaded to PBI Service. Next TV 6000.

**Comment by CesarITD** [comment]
Fixes to 6000:
- Update to -> Leads Count = 
CALCULATE (
    [Leads Count Root],
    FILTER (
        Leads,
        Leads[Is Spam] = "No"
            && Leads[status] <> "Duplicate_Dial"
            && NOT ( Leads[suspect] ) IN { -1, 1 }
    )
)


- All pages filter "Lead Status is not Duplicate_Dial" was take out.

TV 6000 was uploaded to PBI Service.
