### ISSUE TITLE
HK: AWKO Roundup Details 3: Modify Cases by Cancer Type table to host Cancer Stage

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#357]
Converted to a Matrix:
![image](https://user-images.githubusercontent.com/50643267/69647362-58f63e80-1037-11ea-9dc0-64fef4b3469e.png)

Created measure `Cases % All Stages` for the row-level %:
`Cases % All Stages = DIVIDE ( [Cases Count w Blanks], CALCULATE ( [Cases Count w Blanks], ALLSELECTED ( 'Cases'[Roundup Cancer 1 Stage] ) ) )`

**Comment by jesusitd** [comment]
Deployed to AWKO, hidden tab Roundup Details 3.

**Comment by CesarITD** [comment]
Last one: Davis Bethune Jones Campaigns.pbix

**Comment by CesarITD** [comment]
Deployed all Firms.
