### ISSUE TITLE
Change Tracking Process in the Facebook Ads Tables

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#365]

**Comment by CesarITD** [comment]
Approval Document:


[Facebook Tracking Log Solution v02.docx](https://github.com/intakedesk/PowerBI-General/files/3906353/Facebook.Tracking.Log.Solution.v02.docx)

**Comment by CesarITD** [comment]
Document: Technical Documentation of Facebook Tracking Log Solution.

Author(s): Cesar Moncada.
Date: Oct-31-2019
Update dates: 

General Description
The solution was designed with these features:
-	Capture change log in the Facebook Configuration Tables every hour.
-	Creation of reports that allow to visualize date time of when a registry underwent any change (new registration or modification of some field)

Facebook Configuration Tables
-	AdAccounts
-	Campaigns
-	AdSets
-	Ads

**Comment by CesarITD** [comment]
Approval of the CData Sync - Faceboook Ads Solution is expected.

**Comment by jesusitd** [comment]
The 4 Scheduled Tasks have been deployed to 18.209.97.85:
![image](https://user-images.githubusercontent.com/50643267/80009032-7fa98b80-8496-11ea-813a-333b1bf37c53.png)

Task Scheduler is using Python MySQL Stored Procedures utility https://github.com/intakedesk/py-mysql-stored-procedures

Will monitor and release by email. Recommended to implement logging. https://github.com/intakedesk/py-mysql-stored-procedures/issues/2

**Comment by jesusitd** [comment]
Tech Specs
[Facebook.Tracking.Log.Solution.v03.docx](https://github.com/intakedesk/PowerBI-General/files/4517901/Facebook.Tracking.Log.Solution.v03.docx)
