### ISSUE TITLE
Eduardo: Support with CData Sync process to Dev Master DB.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#367]

**Comment by jesusitd** [comment]
Closed with several other CData issues after contacting CData support and installing LeadConduit tables on DEV2 with CData Sync.

**Comment by CesarITD** [comment]
It still open. Ed is preparing a Table List to continue with the creation of DB Core to copies.

**Comment by jesusitd** [comment]
Hi @CesarITD can we close this?

**Comment by CesarITD** [comment]
This project was put on hold.
