### ISSUE TITLE
Changes for Launch 6000 with Hernia Mesh

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#369]

**Comment by CesarITD** [comment]
Pending:
- "Lead Form - Hernia Mesh" Tab need setup for Lead Type (no current transactions).
- To create "Cost Analysis - Hernia Mesh"

For 2000 and 3000: To create "Cost Analysis - Hernia Mesh"

**Comment by jesusitd** [comment]
Deployed by @CesarITD .

Done.
