### ISSUE TITLE
3000: Run tests with new Hernia Mesh Lander to ensure reporting is up to challenge

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#374]

**Comment by CesarITD** [comment]
The first test Leads were received and the report has already been reviewed by HK.

**Comment by jesusitd** [comment]
3000 and LVA got the changes deployed including transformations to `Implant Year` and `Revision Scheduled` fields

**Comment by jesusitd** [comment]
Done.
