### ISSUE TITLE
Nick: Reply email with Campaigns  association of Lead Type and Account

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#387]
Nick:

All,
Good news, we have updated the CRM to support associating a specific Account (Law Firm) and product (Tort) with CRM campaigns. In fact we have done even better than make it an optional field, it is now required for the new Dialer to operate. This should also help with reporting. So while we have built the association, I do need help backfilling the data. For as many campaigns in the CRM as a possible can you please help me fill in the data (product_id, account_id)?
 
Thanks,
Nick

**Comment by jesusitd** [comment]
Analyzed on file:
[campaigns.xlsx](https://github.com/intakedesk/PowerBI-General/files/3981146/campaigns.xlsx)

Generated 358 updates total:
[STATEMENTS UPDATE.txt](https://github.com/intakedesk/PowerBI-General/files/3981151/STATEMENTS.UPDATE.txt)

@nmusco  Done. Take a look and run if you agree

**Comment by nmusco** [comment]
Thank you, I have imported this and am working on figuring out what to do with the 37 remaining campaigns.
