### ISSUE TITLE
Create Monitor for FacebookInsights integration

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#397]
Working on several monitor tabs on `Performance Monitor` report. 

CC @CesarITD

**Comment by jesusitd** [comment]
There's a chance we can close this with Performance Monitors report already running?

@CesarITD 

![image](https://user-images.githubusercontent.com/50643267/73103609-76724800-3ec2-11ea-8a1e-b2bcaf8be009.png)

**Comment by CesarITD** [comment]
![image](https://user-images.githubusercontent.com/54183399/73103804-e385dd80-3ec2-11ea-87ef-9f702ad87078.png)

**Comment by CesarITD** [comment]
Yes. It task is closed with the reports in Performance Monitors.PBIX
