### ISSUE TITLE
Set up LeadConduit data warehousing to start reporting

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#40]
This is for following up on the data download to database.

**Comment by jesusitd** [comment]
@nmusco Please let me know when the DB is ready, and kindly grant me access to it.

**Comment by jesusitd** [comment]
Hi @nmusco please provide me read/write access to Lead Conduit DB to start programming the scraper.

Still need to take final decision:
- Azure Function (C#)
- On premises C# console program
- On premises Python program.

I can go for the Azure Function even though the learning curve will be steeper than that of Py for me.

**Comment by jesusitd** [comment]
Hi @CesarITD please use this issue to write down your notes regarding this matter that HK brought to attention yesterday thanks

**Comment by CesarITD** [comment]
Suggestion. In order to have full control of the data flow of this type of data source, two things are necessary:
1. Keep the data more than 90 days, since the Conduit System is keeping just 90 days.     2. Have a field that allows the relation between the record in Conduit with the record that entered in the CRM system.

**Comment by jesusitd** [comment]
We can use CData Sync to start doing this. We need to start populating the lead-conduit tables we have in the MySQL schema.

@CesarITD can you help me copying this schema into the same Facebook database on Dev 2???

Hi @fedegarza **can you please provide us with a DB according to these specs so we can run Tests on it???** Gracias!
- Server: crm.dev2.intakedesk.com
- DB Name: lead_conduit
- User privileges: All privileges ONLY WITHIN this lead_conduit database, so we can create and write Tables

Goal is to test CData Sync to see if we can get to replicate LeadConduit data into our database. We already have the LeadConduit API access.

**Comment by jesusitd** [comment]
**STARTED TESTS WITH CDATA SYNC**

Successfully replicating `flows` table.

Target schema tables to replicate:
- **DONE** entities
- **DONE** entities_flows
- **DONE** entities_modules
- **DONE** event_statistics
- **DONE** events ->  Lots of comments + Python Utility
- **DONE** fields
- **DONE** flow_fields
- **DONE** flow_sources
- **DONE** flow_steps
- **DONE** flows
- **DONE** integration_metadata
- **DONE** integration_packages
- **DONE** sources

**Comment by jesusitd** [comment]
Schema Comments:

**RECONSIDER USING NULLABLE ENUMS**

**entities**
- `field_suffix` must be nullable
- `deprecated` must be nullable
- `created_at` must be nullable
- `updated_at` must be nullable
- `account` must be nullable
- `source` can't be enum due to nulls -> set to `varchar(50)`
- `recipient` can't be enum due to nulls -> set to `varchar(50)`
- To support inner XPATH `/flow_ids/` and save connections space, use `DISTINCT` in `SELECT` statement

**fields**
- `deprecated` must be nullable
- `created_at` must be nullable
- `updated_at` must be nullable
- `type` can't be enum due to nulls -> set to `varchar(50)`

**events**
- LIMIT of 1000 records returned per call. Must be parameterized. http://docs.activeprospect.com/leadconduit/resources.html#events
- Parameterized URI query using "after_id" and "sort" (ASC) parameters. Using Task Scheduler, a Python utility grabs the last event_id by timestamp, then PUT the CData Connection with the API setting the new "after_id" parameter :), then `executeJob` with same API. 🥇 
- `version` is not a JSON object in the call
- `start_timestamp` must be changed to `bigint(20)` (in milliseconds)
- `end_timestamp` must be changed to `bigint(20)` (in milliseconds)
- `outcome` can't be enum due to nulls -> set to `varchar(50)`

**sources**
- `source_id` must be changed to `char(24)`
- In order to change the data type for `source_id`, one must drop 2 foreign keys first: `flow_sources` FK3 and `events_statistics` FK2. -> Just recreate the 2 tables using DDL
- The `REPLICATE` statement in the CData Job uses `SELECT DISTINCT` :)

**entities_flows** 🥇 
- Try JSON Connector instead, if doesn't work, Contact CData support for Job `LC-ENTITIES-FLOWS`
...
- Worked around with Custom Azure API **temporarily** 👎 . This API fills up the `entities` call with the missing suitable objects to overcome the anonymous `flow_ids` list issue.
- Job: `lcent2`.
- Set up in "TRUNCATE TABLE" mode

**entities_modules**
- Same method as **entities_flows**

**flow_steps**
- Added `entity_name` and `description` (for filter type) columns to make more readable table.
- Uses `steps.id` as `step_id`, but numbers are absolute to the whole set created by CData instead of relative to each flow. Okay for now.
- Job: `LC-FLOWS` using `DISTINCT` and XPATH `/step/`
- Had to Add `description` field in CUSTOM SCHEMA, as the auto generator is not generating it

**flow_fields**
- Job: `LC-FLOWS` using `DISTINCT` and XPATH `/fields/`

**flow_sources**
- Job: `LC-FLOWS` using `DISTINCT` and XPATH `/sources/`

**integration_packages** -> RENAMED **packages**
- From `packages` resource
- Deserializing with `packages/integrations` as well to use one connection only, and deduping using `DISTINCT` :)

**integration_metadata** -> RENAMED **package_integrations**
- Modified `median_wait_ms` to be nullable
- `type` can't be enum due to nulls -> set to `varchar(50)`

**events_statistics**
- Can't group by `step_id` -> lost granularity point because it can't be accessed by the `group_by` parameter
- Saved Daily, in UTC Timezone
- Columns added: `source-submitted`, `source-success`, `source-failure`, `source-error`, `recipient-submitted`, `recipient-success`, `recipient-failure`, `recipient-error`, `filter-success`, `filter-failure`, `filter-error`, to slice by `type` since the API does not return a `type` property but allows to grab these stats already sliced
- MUST BE HELPED WITH PYTHON LAUNCHER since the date range must be dynamically updated. Any other solution welcome

**Comment by jesusitd** [comment]
For CData Sync, one can use the `CreateSchema` Stored Procedure to generate schema XML files and work with them.

`EXECUTE [CreateSchema] @TableName="events-stats", @URI="https://next.leadconduit.com/events/stats", @XPath="/", @FileLocation="/home/jetty/cdata/datasync/schemas/"`

Generating:
```xml
<api:script xmlns:api="http://apiscript.com/ns?v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- See Column Definitions to specify column behavior and use XPaths to extract column values from JSON. -->
  <api:info title="events-stats" desc="Generated schema file." xmlns:other="http://apiscript.com/ns?v1">
    <!-- You can modify the name, type, and column size here. -->
    <attr name="end"                 xs:type="date"    readonly="false"              other:xPath="/json/end"                 />
    <attr name="filter-error"        xs:type="integer" readonly="false"              other:xPath="/json/filter-error"        />
    <attr name="filter-failure"      xs:type="integer" readonly="false"              other:xPath="/json/filter-failure"      />
    <attr name="filter-success"      xs:type="integer" readonly="false"              other:xPath="/json/filter-success"      />
    <attr name="json:_id"            xs:type="string"  readonly="false"  key="true"  other:xPath="/json/_id"                 />
    <attr name="recipient-error"     xs:type="integer" readonly="false"              other:xPath="/json/recipient-error"     />
    <attr name="recipient-failure"   xs:type="integer" readonly="false"              other:xPath="/json/recipient-failure"   />
    <attr name="recipient-submitted" xs:type="integer" readonly="false"              other:xPath="/json/recipient-submitted" />
    <attr name="recipient-success"   xs:type="integer" readonly="false"              other:xPath="/json/recipient-success"   />
    <attr name="source-error"        xs:type="integer" readonly="false"              other:xPath="/json/source-error"        />
    <attr name="source-failure"      xs:type="integer" readonly="false"              other:xPath="/json/source-failure"      />
    <attr name="source-submitted"    xs:type="integer" readonly="false"              other:xPath="/json/source-submitted"    />
    <attr name="source-success"      xs:type="integer" readonly="false"              other:xPath="/json/source-success"      />
    <attr name="start"               xs:type="date"    readonly="false"              other:xPath="/json/start"               />
    <attr name="vars.flow.id"        xs:type="string"  readonly="false"              other:xPath="/json/[vars.flow.id]"      />
    <attr name="vars.source.id"      xs:type="string"  readonly="false"              other:xPath="/json/[vars.source.id]"    />
  </api:info>

  <api:set attr="DataModel" value="FLATTENEDDOCUMENTS" />
  <api:set attr="URI" value="https://next.leadconduit.com/events/stats" />

  <api:set attr="JSONPath" value="/" />

  <!-- The GET method corresponds to SELECT. Here you can override the default processing of the SELECT statement. The results of processing are pushed to the schema's output. See SELECT Execution for more information. -->
  <api:script method="GET">
    <api:call op="jsonproviderGet">
      <api:push/>
    </api:call>
  </api:script>

  <!-- To add support for INSERTS please see the INSERT Execution page within the help for further information and examples. -->
  <api:script method="POST">
    <api:set attr="method" value="POST"/>
    <api:call op="jsonproviderGet">
      <api:throw code="500" desc="Inserts are not currently supported."/>
      <api:push/>
    </api:call>
  </api:script>

  <!-- To add support for UPDATES please see the UPDATE Execution page within the help for further information and examples. -->
  <api:script method="MERGE">
    <api:set attr="method" value="PUT"/>
    <api:call op="jsonproviderGet">
      <api:throw code="500" desc="Updates are not currently supported."/>
      <api:push/>
    </api:call>
  </api:script>

  <!-- To add support for DELETES please see the DELETE Execution page within the help for further information and examples. -->
  <api:script method="DELETE">
    <api:set attr="method" value="DELETE"/>
    <api:call op="jsonproviderGet">
      <api:throw code="500" desc="Deletes are not currently supported."/>
      <api:push/>
    </api:call>
  </api:script>

</api:script>
```

**Comment by jesusitd** [comment]
**`REPLICATION` Update, with CData support**

**Comment by jesusitd** [comment]
Final Comments coming up next in Solution Documentation release

**Comment by jesusitd** [comment]
Final comments in this documentation:
[CData Sync LeadConduit Documentation.docx](https://github.com/intakedesk/PowerBI-General/files/3963141/CData.Sync.LeadConduit.Documentation.docx)

Pending migration to production. That implementation will be tracked separately.
