### ISSUE TITLE
Hernia Mesh Clients proposal: Create new tab with visuals using new data points are per recent changes in the CRM (AWKO Test)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#407]
Conversation with Eduardo: Ideas for visuals/data points:

Dimensions:
- Number of Implants
- Had Revision
- Revisions Count
- Has Scheduled Revision
- Revision too Dangerous to Perform
- JG: Revisions vs Sched Revisions (2x2 combination, create something meaningful)
- Product in Place: No Revision or Has a 2nd Implant that has no revision. Represents a PNC (potential new client) in the future

Facts:
- Cases Count
- Cases %

Jesus:
Could also take chance to:
- Clean up billable Donut as per last definition (check GH Issue)
- Include NEW CARDS that COUNT CASES. Highly needed. Not available (incredibly)
- Develop (if possible) a table visual of Leads in the Pipeline to complete the Packages Sent that don't have a Case yet.

Additionally, from Case Overview (CRM):
![image](https://user-images.githubusercontent.com/50643267/71931556-f16dfb80-316b-11ea-80af-a6915228858f.png)
- HERNIA TYPE
- HERNIA LOCATION
- Complication Type for Case Details

**Comment by CesarITD** [comment]
- Area Implant Visual ( If is possible a Body Map)
- Count of Leads with 2 or more Implants

**Comment by jesusitd** [comment]
ETL Checklist:
- Number of Implants
- DONE Had Revision
- DONE Revisions Count
- DONE Has Scheduled Revision
- Revision too Dangerous to Perform
- Revisions vs Sched Revisions (2x2 combination, create something meaningful)
- Product in Place: No Revision or Has a 2nd Implant that has no revision. Represents a PNC (potential new client) in the future
- HERNIA TYPE -> CREATED DATAFLOW ENTITY **`CasesHerniaMeshImplantTypes`**
- HERNIA LOCATION -> Imported **`Hernia Mesh Original Implant Area`** as column to Cases dataflow (table)
- Complication Type for Case Details -> Transform into String

Model/ETL checklist (TBD):
- Develop (if possible) a table visual of Leads in the Pipeline to complete the Packages Sent that don't have a Case yet.

**Comment by jesusitd** [comment]
Current situation of proposal tab:
![image](https://user-images.githubusercontent.com/50643267/72047542-c2997780-3288-11ea-9ed5-e61173030383.png)

**Comment by jesusitd** [comment]
Released as Hidden tab "NEW Hernia Mesh Details 2" and waiting on HK comments/approval.

![AWKO Hernia Details 2](https://user-images.githubusercontent.com/50643267/72115184-2fa61f00-3314-11ea-93b7-052b75834280.png)

**Comment by jesusitd** [comment]
Solution assumed accepted.
