### ISSUE TITLE
Genesys: Request user access for Cesar and Jesus to start exploring the data and reporting opportunities

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#410]

**Comment by CesarITD** [comment]
Research:
Nick said that all genesys data available is in Elastic Search. We need look for there.

Jesus for your information try to login here with Microsoft option: https://login.mypurecloud.com/
I suggested you ash a Genesys Account to have other communication option with us.

**Comment by jesusitd** [comment]
Hi Nick, I am trying to access the link below to start exploring the data/reports regarding the Genesys implementation.

Can I get a login to  https://login.mypurecloud.com/ ?

**Comment by CesarITD** [comment]
https://developer.mypurecloud.com/forum/t/api-vs-reporting/4330

Hello,

We are building out an integration with your API to display aggregated PureCloud call data in our reporting tool.
Do you have a data dictionary for each report in how the various reports are built or how the data from the API rolls up to the report? I.E. How is the Offered metric in a Queue Metrics Daily Report built? Is it on a per-conversation or per-segment basis?

Sorry if it does exist somewhere and we're just blind. We were referred to post our questions here by our PureCloud Genesys contact Zach Hinkle.

Thanks for your help in advance.

--------------

There isn't a traditional data dictionary. Take a look at the Analytics APIs documentation 78, which includes information about the metrics and definitions. Use the Analytics Query Builder 65 to build and run analytics queries in your org without writing any code.

The various views and reports in PureCloud are documented here: https://help.mypurecloud.com/articles/about-reports-views-and-dashboards/ 43

**Comment by jesusitd** [comment]
I managed to log into My Pure Cloud with my email.

Can I get an extension number??? @nmusco 

@CesarITD

**Comment by nmusco** [comment]
Jesus,
Your extension is 9005.

**Comment by jesusitd** [comment]
Done.
