### ISSUE TITLE
HK: CREATE for Client Hernia Mesh Napoli a version of 2.0 for PIPELINE REPORTS - Realtime Stats

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#412]
I created a new dataset from Tort Vision 2.0:
`C:\Users\jesus\Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\- Datasets\For Firms\Napoli - Tort Vision.pbix`

Size: ~29MB
The file was shrunk down in size by filtering PID 1010 in leads, and by filtering dates 2020-1-1+ for these tables:
- AdsInsights
- OfflineResults
- Cases
- LeadsCalls
- Documents

A tab was created "Hernia Mesh - Realtime" from Pipeline Reports/Realtime Campaign Stats.

This will be the template for the new report

**Comment by jesusitd** [comment]
Need to discuss about what needs to be done with the report.

I leave my notes here:
![image](https://user-images.githubusercontent.com/50643267/72306960-be81a700-3646-11ea-8698-0f39f4dad49d.png)

I notified HK via SMS. Can you send email tomorrow? Thank you @CesarITD

**Comment by CesarITD** [comment]
Report "Napoli Exclusive - Tort Vision.pbix" was created

**Comment by jesusitd** [comment]
I'm sending an SMS to HK so he notices it
