### ISSUE TITLE
UPDATE PID 2000 invalid Subid_c (165 records)

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#416]
Provided list of leads with `invalid` Sub ID to PID 2000, to run a SQL UPDATE.

They replied back with this spreadsheet (plus a couple calculated columns):

[Invalid Ad ID Number Reconciliation_1.10.2020.xlsx](https://github.com/intakedesk/PowerBI-General/files/4077729/Invalid.Ad.ID.Number.Reconciliation_1.10.2020.xlsx)

**Comment by jesusitd** [comment]
[416- Update 2000 invaiid 165 records.txt](https://github.com/intakedesk/PowerBI-General/files/4077739/416-.Update.2000.invaiid.165.records.txt)

Hi @nmusco can you please run this UPDATE???? It was left outstanding on 1/10/20. Thanks!

**Comment by fedegarza** [comment]
Done
