### ISSUE TITLE
RS: Create a Report to show suppression list entries and provide a mechanism to review these cases in order to notify the Firm

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#419]
Let's bring this up wit recent Suppression List push @CesarITD @fedegarza

**Comment by jesusitd** [comment]
Operations -> Duplicates Leads and Cases -> Suppressed Leads:

![image](https://user-images.githubusercontent.com/50643267/73676699-d2875a00-4682-11ea-8762-7ded19385a69.png)

This still doesn't provide a mechanism to scrub against the source suppression case, depending of:
- Whether it's an Intake Desk case or an External Source Case
- No specific way (currently) to determine the one specific case that matched

STILL NEED to provide the available details of the matched source case.

**Comment by jesusitd** [comment]
No further details requested so far...

**Comment by jesusitd** [comment]
This has been replaced with issue #580 .

Notifications for firms will be kept as a backlog idea since the process is still too immature.
