### ISSUE TITLE
Hernia Mesh: Complete the definition to BI Reports with Management what is the qualification rule for Hernia Mesh

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#446]

**Comment by jesusitd** [comment]
Published Smartsheet "BI Lead Form Qualification Rules Criteria"
https://app.smartsheet.com/sheets/Q5fpGGHh94VqWmJxF3Jw78w6gxQVHrJc4mV3VcX1

**Comment by jesusitd** [comment]
This is closed until new requirements regarding qualification rules arise.

CC @CesarITD 

Done.
