### ISSUE TITLE
Pid3000 Talc Call Notes 2-12-20 5pm

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#456]
RS:

is trust form getting pid3000 talc lead form activity

78 leads are missing

what is definition of CPLQ? what is qualified on Talc

note that 2-13-20 is when a/b test started on talc pid3000

how is projected CPS factored? pid3000 Tortvision Campaigns Analysis

everything needs to be defined - every KPI filtering/criteria

**Comment by CesarITD** [comment]
Some were answered by email and the remaining tasks will be handled as separate Issues.
