### ISSUE TITLE
HK: HK need visibility of Leads stucks in Leadconduit in what Step/Validation is the Lead.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#458]

**Comment by jesusitd** [comment]
Use LeadConduit Sync Monitor for this.
https://app.powerbi.com/groups/3e84394e-0c4b-4389-89e2-0f43d7da97d1/reports/bf1a076d-9732-4781-9b7d-4c888fa69baa/ReportSection79e92b35613032e41d6e

Might need to Add a Lead attribute to indicate the last step of the Lead (the one where it might have got stuck)

CC @CesarITD

**Comment by jesusitd** [comment]
Another interpretation might be:
- Did it have a FORM POST? along with
- What was the last Step?

**Comment by jesusitd** [comment]
Added Stuck Leads measure, for `Leads[Form POST Outcome] <> "success"` to LeadConduit Sync Monitor report.

- ~~Pending adding Last Event Reason (for the one step where they got stuck).~~
- ~~PENDING ACCEPTANCE CRITERIA (FLOW ACCEPTANCE OUTCOME AND REASON)~~ There is no acceptance criteria anymore

**Comment by jesusitd** [comment]
Released on email w/ Subject "LeadConduit Monitor" this Friday 2/21/20.

Done.

Further requests will be handled separately.
