### ISSUE TITLE
A-B Landing Comparison between Landing of different Providers

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#459]

**Comment by jesusitd** [comment]
Done for PID 2000, "Hernia Mesh Vertical Lander Comparison":

![image](https://user-images.githubusercontent.com/50643267/74590792-aa332000-4fdf-11ea-9418-4bdd76ad836e.png)

Pending others

**Comment by jesusitd** [comment]
Deployed for 3000 by @CesarITD.

**Comment by jesusitd** [comment]
Need to to this for Lead Vision Ads @CesarITD , I'll be working on this

**Comment by jesusitd** [comment]
Deployed to Lead Vision Ads.
![lander-side-by-side](https://user-images.githubusercontent.com/50643267/74687564-c8954900-51a2-11ea-998e-8f78c1aee08c.png)

Done.
