### ISSUE TITLE
Correct wrongly posted SubId - Source from 2000 during 06-11th thru 13th, by UPDATE SQL on DB

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#46]
Run UPDATE statements to swap back sub id an campaign source for wrongly posted Leads from 2000.

**Comment by jesusitd** [comment]
@nmusco Kindly let me know what are the filter parameters we use to chase these Leads down.

I will be making the SQL Updates right after

**Comment by nmusco** [comment]
Nothing I can do with this one until I get the data

**Comment by jesusitd** [comment]
Okay. Let's wait for 2000 to provide the Ad Ids corresponding to these leads.

**Comment by nmusco** [comment]
attached I the spreadsheet with the updates, please create the queries for me to execute
[2000 Wrong Ad ID_updated6.13.19.xlsx](https://github.com/intakedesk/PowerBI-General/files/3288025/2000.Wrong.Ad.ID_updated6.13.19.xlsx)

**Comment by jesusitd** [comment]
@nmusco Please find the UPDATE statements in the last column of the spreadsheet:

[2000.Wrong.Ad.ID_updated6.13.19.xlsx](https://github.com/intakedesk/PowerBI-General/files/3288066/2000.Wrong.Ad.ID_updated6.13.19.xlsx)

**Comment by nmusco** [comment]
This has been updated
