### ISSUE TITLE
HK: Add Sign/Decline to 3000 Campaigns Analysis and AdSets Analysis

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#470]

**Comment by jesusitd** [comment]
Deployed.

Waiting comments.

![adsets](https://user-images.githubusercontent.com/50643267/74776851-54bc7480-5266-11ea-9bd0-b064355958c3.png)

**Comment by jesusitd** [comment]
Assumed approved.

Must be deployed for LVA and 2000 (Hidden)

**Comment by CesarITD** [comment]
2000 (AdSets Analysis and Campaigns Anlysis) Done. Now just pending LVA.

**Comment by jesusitd** [comment]
Deployed AdSets Analysis and Campaigns Analysis to Lead Vision Ads:
![image](https://user-images.githubusercontent.com/50643267/75590437-51d23880-5a4b-11ea-9897-9ef85bdadf1c.png)

Done.
