### ISSUE TITLE
Bi Report to DNQ Data. Side by side comparison of Lander Questions vs Intake Data

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#475]

**Comment by CesarITD** [comment]
Three critical points for DNQ only:
        - Lead Form Answer
	- Decline Reason
	- Intake Field

Suggested order:
        - Tackle Detail
	- Tackle aggregation

For DNQ Criteria:
        - Status is DNQ
	- or Current Dispo _C is DNQ
	- or id_intake_hernia_mesh.hernia_mesh_decline_reason is NOT NULL

**Comment by CesarITD** [comment]
it was send to revision

**Comment by jesusitd** [comment]
This was delivered with "HERNIA Declined - Lead Form vs. Intake" in Data Sweep - Operations report.
![image](https://user-images.githubusercontent.com/50643267/80991765-81fcd580-8e06-11ea-83ae-93ac783ee09d.png)
