### ISSUE TITLE
Move Slave 2 tables and reports to either Production 2 or CRM.intakedesk

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#484]
@CesarITD please leave any comments and task lists done below here thanks!

**Comment by jesusitd** [comment]
Refresh Server task scheduler (**all disabled**):
- ~~CData Sync Leads~~ Updated SQL Connection in Credentials.json - (py-cdata-sync)
- ~~CData Sync Events~~ Updated SQL Connection in Credentials.json - (py-cdata-sync)
- ~~CData Sync Events-Stats~~ Updated SQL Connection in Credentials.json - (py-cdata-sync)
- Run Py MySql Leads Duplicates Generator **NEED TO CREATE DB IN PRODUCTION**
- Run Py MySql Suppressed Leads Generator **NEED TO CREATE DB IN PRODUCTION**
- ~~Run Python MySQL Replication Check~~ Removed Slave 2 from Host Check (py-mysql-monitor)

**Comment by jesusitd** [comment]
CData Sync Connections to be reconfigured:
- ~~ID - MySQL - Facebook - Dev2~~
- ~~ID - MySQL Slave 2 - LeadConduit~~

From Power BI report on CData Sync REST API info:
![image](https://user-images.githubusercontent.com/50643267/76124531-e0553580-5fc8-11ea-9380-d6adfddb5ce9.png)

For FB:
![image](https://user-images.githubusercontent.com/50643267/76125859-b4877f00-5fcb-11ea-9431-f2dc76f9113c.png)
For LC:
![image](https://user-images.githubusercontent.com/50643267/76125877-bfdaaa80-5fcb-11ea-8acb-0f5615e2ef64.png)

**Comment by CesarITD** [comment]
Done (move to PRD2): LeadConduit Sync Monitor.pbix and PID 3000 - CData - Tort Vision.pbix
Pending (move to slave1): Datasets related with BI Utilities objects.

**Comment by jesusitd** [comment]
The remainder of this issue is duplicated here: https://github.com/intakedesk/py-mysql-stored-procedures/issues/1

Closed.
