### ISSUE TITLE
ZANTAC. Deploy Landers and Bi reporting

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#511]
Landing page from 3000 Done.

**Comment by jesusitd** [comment]
In progress as per Smartsheet tracking page:
https://app.smartsheet.com/sheets/QJ6X5hhMWrh8grrqFphvwmpC443H2gqp6x52f6G1

**Comment by jesusitd** [comment]
Working on setting up reports

**Comment by CesarITD** [comment]
3000 Done. (Pending Qualification Rule)
2000 working by Cesar.
Lead Vision Ads by Jesus

**Comment by CesarITD** [comment]
2000 done. It is UP.

**Comment by jesusitd** [comment]
Working on 2.0

Pending Azure AS

**Comment by jesusitd** [comment]
2.0 and Lead Vision Ads done. CC @CesarITD

**Comment by jesusitd** [comment]
Deployment of landers and reporting done.

Just waiting for campaign to start.
