### ISSUE TITLE
RETURNED MESSAGES Callbacks report: Add some sort of day trend

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#513]

**Comment by CesarITD** [comment]
Taking

**Comment by CesarITD** [comment]
In revision by HK

**Comment by jesusitd** [comment]
DONE.
![image](https://user-images.githubusercontent.com/50643267/81007273-ed52a180-8e1e-11ea-814c-f7a8cf2ddd08.png)

Outdated revision.
