### ISSUE TITLE
CRM Tasks assigned report

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#520]

**Comment by CesarITD** [comment]
On Apr 15, 2020, at 7:43 PM, Richard Smith <richard@intakedesk.com> wrote:
We need to see tasks assigned by Brandie in the CRM and who she assigned them to. I tried to pull it up in the Tasks module in the CRM but theres no selection for who created the task


-------------------
From: Howard Knaster <howard@intakedesk.com>
Date: Wednesday, April 15, 2020 at 8:35 PM
To: Richard Smith <richard@intakedesk.com>
Cc: Nicholas Musco <nick@intakedesk.com>, Eduardo Garza <egarza@intakedesk.com>, Jesus Gonzalez <jesus@intakedesk.com>
Subject: Re: CRM Tasks assigned report

Richard- 

Specifically these Tasks are related to CBs or Missed CBs or some type of follow call being assigned to an intake rep or another person on team by Brandie when she “sweeps” .  This entire process she goes through not only is not efficient but it’s not being tracked.  This needs serious attention.

**Comment by jesusitd** [comment]
Released tab "Tasks" in REMOTE AGENTS.
![tasks remote](https://user-images.githubusercontent.com/50643267/79577123-3ae6b480-8092-11ea-886c-9f29b849afbf.png)

**Comment by jesusitd** [comment]
Report no longer under scope.

Considered released.
