### ISSUE TITLE
New reports in PBI using Vicidial data.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#527]

**Comment by CesarITD** [comment]
New DB and new Tables was created in PROD2. New Integration  using CData Sync is being development. Now we need new credentials to new Vicidial DB

**Comment by jesusitd** [comment]
CC @fedegarza

**Comment by jesusitd** [comment]
CData is looking into Bad Handshake error. CC Ted K. (CData Support)

**Comment by jesusitd** [comment]
This was not looked into anymore. Will be replaced by Genesys.
