### ISSUE TITLE
Talcum: Remove some Cancers from BI Qualified Criteria

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#529]

**Comment by CesarITD** [comment]
From: Richard Smith <richard@intakedesk.com> 
Sent: Monday, April 27, 2020 5:19 PM
To: Jesus Gonzalez <jesus@intakedesk.com>; Howard Knaster <howard@intakedesk.com>
Cc: Cesar Moncada <cmoncada@intakedesk.com>; Eduardo Garza <egarza@intakedesk.com>
Subject: Re: TALC
 
Per our discussion. Jesus/Cesar are going to remove Mesothelioma, Endometrial and Uterine Cancer from all PID CPLQ filters. They understand that just because Lead Conduit criteria has a lead posting to the A campaign, it doesn’t necessarily make it Qualified for Bi criteria. Jesus is going to update us as soon as they have updated all filters.
 
Sidenote (not necessary for CPLQ update): HK noted that we need Non-Qualifying cancer types to be entered. Also wanted to check on borderline mucinous tumor for qualifying?

**Comment by CesarITD** [comment]
Richard:
Thanks. Lets keep an eye on it over the next few days to ensure we didn’t miss anything. Let’s update the Non-Qualifying Cancer Types table for Talc too. Not a top priority. Whenever you guys get a sec.

**Comment by CesarITD** [comment]
'Endometrial Cancer' and 'Uterine Cancer' was removed from 2000, 3000 and 8000. In 2.0 was removed too Mesothelioma.

**Comment by jesusitd** [comment]
From Azure AS:
![image](https://user-images.githubusercontent.com/50643267/80722367-49d75900-8acd-11ea-9777-6259f50913d2.png)
