### ISSUE TITLE
Prepare document to next session with BI Avtex

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#556]

**Comment by CesarITD** [comment]
Megan and HK:
- Sources
- Transformations
- More painful data-points
- Who Maintain the data, manual data and Reports.
- List of our Reports. What we have. Maybe take some examples to explain the document los Details of the report.

What more do you understand Jesus?

**Comment by jesusitd** [comment]
This is likely to be an ongoing task.

For now, some outstanding topics:
- Discuss about Deliverables with AVTEX (Formal document with all the technical recommendations, including approach, infrastructure, services, architecture, reporting techniques, reports proposals, etc.)
- PERHAPS finish PID 2000 model/ETL of `LeadVendorAdsInsights` and `LeadVendorAds` which could not be covered during last Fri 5/22/20 session.

**Comment by jesusitd** [comment]
All sessions. Done.
