### ISSUE TITLE
Query Slow Debug

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#58]
SELECT 
    lc.id_c AS `lead_id`, lc.complications AS 'complications'
FROM
    leads
        JOIN
    (SELECT 
        id_c,
            NULLIF(TRIM(BOTH ',' FROM TRIM(BOTH ' ' FROM CASE
                WHEN xarelto_side_effects_c = '^^' THEN NULL
                ELSE xarelto_side_effects_c
            END)), '') AS 'complications'
    FROM
        leads_cstm) lc ON leads.id = lc.id_c
WHERE
    lc.complications IS NOT NULL
        AND leads.deleted = 0

**Comment by nmusco** [comment]
```sql
SELECT	lc.id_c AS lead_id, 
	NULLIF(TRIM(BOTH ',' FROM TRIM(BOTH ' ' FROM CASE WHEN xarelto_side_effects_c = '^^' THEN NULL ELSE xarelto_side_effects_c END)), '') AS 'complications'
FROM 	leads
JOIN 	leads_cstm lc ON leads.id = lc.id_c
WHERE 	lc.xarelto_side_effects_c IS NOT NULL
	AND TRIM(lc.xarelto_side_effects_c) <> ','
	AND TRIM(lc.xarelto_side_effects_c) <> '^^'
	AND leads.deleted = 0;
```
