### ISSUE TITLE
Duplicates Leads and Cases redesign

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#580]
Evaluate Pentaho as the way to go for the integrations part of this issue.

Pentaho Data Integrations documentation:
https://it4biz.gitbooks.io/pentaho-bi-for-all/content/presenting_pdi.html

**Comment by CesarITD** [comment]
- External Suppression Lists. Load all external list and update bridge.
- New Tab. Depud all vs all. To create a solution with views. To add Sequence ID to step2 looking for perfomance. 
  - -  IDEA: Try to do the cross-list analysis using a 2-column table with all the Surrogate-Key interactions from MasaterStep2. With this table, the interactions might be calculated in DAX and the Case details be pulled with more DAX Measures. (Need to create a query for the 2-column table with the necessary interactions)

**Comment by CesarITD** [comment]
DONE Report 3 of 5: Matches (dedups) of External Cases List 1  vs External Cases List 2
-- Report 4 of 5: External Cases List 1 vs CRM Leads
-- Report 5 of 5: External Cases List 1 vs CRM Cases

**Comment by jesusitd** [comment]
Thanks @CesarITD great job here. Will close the card and handle changes as subsequent requests.

Published in Operations workspace: https://app.powerbi.com/groups/3e84394e-0c4b-4389-89e2-0f43d7da97d1/reports/4386d9b1-d2e5-4c45-965c-dd86cf6e8021/ReportSection6b419dd381500dc044ea
