### ISSUE TITLE
Investigate CData Sync FB_DAILY job with Ads table with high error rate

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#606]
Job `FB_DAILY` is failing too much for only 1 daily run.

I submitted a support ticket with CData:
```
Hi folks

We have a Sync Job with the following specs:
Source: Facebook (ads)
Destination: MySQL
ScheduleCron": "35 1 * * ?",
Replicate query: [REPLICATE [Ads] SELECT [Ads].*, SYSUTCDATETIME() AS [Timestamp] FROM [Ads] WHERE [Target] IN (SELECT [ID] FROM [AdAccounts])

We are having an issue since this query is throwing an error Table 'facebook_sync.Ads_cdata_replicate_temporary_table' doesn't exist (1146)

It is meant to run once a day and it is failing, thus causing to lose the daily updates on this data.

We hope you can give us some help with this issue. I posted the LOG file (INFO level) here for you to review: https://www.dropbox.com/s/givobv0hut71649/FB_DAILY_2020-08-31-01-35-07.log?dl=0

Thanks!
```

**Comment by jesusitd** [comment]
Deactivated 3000 IVC and 3000 Zantac accounts in `FB_DAILY` Job for `Ads`. Moved both to a new `FB_WEEKLY` job for Saturday nights. This change cuts the query size in half (~35K Ads out of ~70K).

**Comment by CesarITD** [comment]
@jesusitd  It is seen that it did not give more error in the last days when reducing the amount of data, is this the final solution?

**Comment by jesusitd** [comment]
That is correct. Let's close this for now.

However, CData Sync support was not effective with this issue. We'll try to circle back to them after we manage to upgrade the version of Sync as they pointed out for support.

CC @fedegarza
