### ISSUE TITLE
EG: Create Process for posting TEST leads into CRM, with specific phone, name, and email

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#608]
Some script to automate landing page testing (unit test) with all the field combinations and scrape LeadConduit's output to validate CAMPAIGN and other required fields.

Must provision a way to mark test leads in LeadConduit:
- FIRST/LAST
- PHONE
- EMAIL
this combination (to be defined) should bypass all the Steps and also mark the lead as a test.

This could be a V1 for a UNIT TESTER for landing pages. All the fields of interest should be audit-able.

V1: Test routing for all Answer combinations. Not landing page aware
V2/1.1: Test routing directly from the landing page.

Landing page unit testing, there must be something out there already,

**Comment by jesusitd** [comment]
There are several options:

**To Test the Flow:**
-  We can use our own Intake Desk source to hit the flow from outside
- We can also use a **`test_itd`** field in the flows to mark the leads as test and bypass steps in LC
- Checking out this Chrome extension https://chrome.google.com/webstore/detail/autofill/nlmmgnhgdeffjkdckmikfpnddkbbfkkk?hl=en allows to store most common fields and Autofills the thing :)
- Works using the Test Leads module of LeadConduit https://next.leadconduit.com/flows/5d07ef4776b7862667a26fa9/edit/test

**Comment by jesusitd** [comment]
Proposed test lead:

| Attribute | Value |
|--| --|
| First Name | Tester |
| Last Name | Intake |
| Phone Number | 9548004347 |
| Email | info@intakedesk.com |
| ZIP Code | 33073 |

**Created field `itd_test_lead_itd` in ZANTAC - VENDORS.**

Basic configuration for Chrome `Autofill` extension:
```csv
### AUTOFILL PROFILES ###,,,,,,
Profile ID,Name,Site,Hotkey,,,
c2,LC Hernia,next.leadconduit.com/flows/[a-f0-9]{24}/edit/test,,,,
### AUTOFILL RULES ###,,,,,,
Rule ID,Type,Name,Value,Site,Mode,Profile
r62,0,"^Select source\.\.\.$","Intake Desk LLC","",0,c2
r63,0,"^pid_itd$","Intake Desk LLC","",1,c2
r64,0,"^campaign_source$","internal","",1,c2
r65,0,"^internal_advertisment_name_itd$","","",1,c2
r66,0,"^campaign_sub_id_1$","1234567890","",1,c2
r67,0,"^order_number_itd$","9999","",1,c2
r68,0,"^source_type_itd$","","",1,c2
r69,0,"^user_agent$","","",1,c2
r70,0,"^first_name$","Tester","",1,c2
r103,0,"^last_name$","Intake","",1,c2
r71,0,"^gender$","","",1,c2
r102,0,"^phone_1$","9548004347","",1,c2
r72,0,"^email$","info@intakedesk.com","",1,c2
r100,0,"^address_1$","","",1,c2
r73,0,"^city$","","",1,c2
r101,0,"^state$","","",1,c2
r74,0,"^postal_code$","33073","",1,c2
r75,0,"^page_name_itd$","","",1,c2
r76,0,"^contact_method_itd$","","",1,c2
r77,0,"^unbounce\.page_id$","","",1,c2
r78,0,"^unbounce\.page_name$","","",1,c2
r79,0,"^unbounce\.page_url$","","",1,c2
r80,0,"^unbounce\.variant$","","",1,c2
r81,0,"^facebook\.campaign_id$","","",1,c2
r82,0,"^facebook\.ad_name$","","",1,c2
r83,0,"^crm_campaign_id_itd$","","",1,c2
r84,0,"^lead_form_hernia_mesh_implant_year_range_itd$","2019","",1,c2
r85,0,"^lead_form_hernia_mesh_revision_year_range_itd$","2020","",1,c2
r86,0,"^lead_form_hernia_mesh_revision_surgery_quantity_itd$","1 additional","",1,c2
r87,0,"^lead_form_hernia_mesh_other_attorney_itd$","No","",1,c2
r88,0,"^lead_form_hernia_mesh_notes_itd$","Some Hernia TEST details","",1,c2
r89,0,"^lead_form_hernia_mesh_page_variant_itd$","","",1,c2
r90,0,"^web_medium_itd$","","",1,c2
r91,0,"^language_itd$","","",1,c2
r92,0,"^salutation$","","",1,c2
r93,0,"^name_suffix$","","",1,c2
r94,0,"^lead_form_placement_itd$","","",1,c2
r95,0,"^asid_itd$","741852963","",1,c2
r98,0,"^cid_itd$","987654321","",1,c2
r99,0,"^landing_page$","","",1,c2
r150,0,"^campaign_source$","","",1,c2
r152,0,"^source_type_itd$","","",1,c2
r153,0,"^user_agent$","","",1,c2
r155,0,"^gender$","","",1,c2
r157,0,"^city$","","",1,c2
r159,0,"^country$","","",1,c2
r160,0,"^page_name_itd$","","",1,c2
r161,0,"^conversion_page_itd$","","",1,c2
r162,0,"^contact_method_itd$","","",1,c2
r163,0,"^lead_form_notes_itd$","","",1,c2
r164,0,"^unbounce\.page_name$","","",1,c2
r165,0,"^unbounce\.variant$","","",1,c2
r166,0,"^facebook_id$","","",1,c2
r167,0,"^facebook\.campaign_id$","","",1,c2
r168,0,"^facebook\.adset_id$","","",1,c2
r169,0,"^facebook\.ad_name$","","",1,c2
r170,0,"^facebook\.ad_id$","","",1,c2
r171,0,"^crm_campaign_id_itd$","","",1,c2
r175,0,"^lead_form_hernia_mesh_seen_doctor_itd$","","",1,c2
r177,0,"^lead_form_hernia_mesh_page_variant_itd$","","",1,c2
r178,0,"^web_campaign_itd$","","",1,c2
r179,0,"^web_medium_itd$","","",1,c2
r180,0,"^page_uuid_itd$","","",1,c2
r181,0,"^language_itd$","","",1,c2
r182,0,"^origin_header_itd$","","",1,c2
r183,0,"^salutation$","","",1,c2
r184,0,"^middle_name$","","",1,c2
r185,0,"^name_suffix$","","",1,c2
r186,0,"^lead_form_device_itd$","","",1,c2
r187,0,"^lead_form_placement_itd$","","",1,c2
r188,0,"^lead_form_platform_itd$","","",1,c2
r189,0,"^asid_itd$","","",1,c2
r190,0,"^platform_itd$","mobile_feed","",1,c2
r191,0,"^placement_itd$","facebook","",1,c2
r192,0,"^aid_itd$","","",1,c2
### AUTOFILL OPTIONS ###,,,,,,
advanced,"[]",,,,,
exceptions,"[]",,,,,
textclips,"[]",,,,,
variables,"[]",,,,,
backup,0,30,,,,
manual,0,,,,,
delay,0,1,,,,
labelmatch,0,,,,,
overwrite,0,,,,,
vars,1,,,,,
sound,1,,,,,
voice,0,1,,,,
debug,0,,,,,
mask,1,,,,,
scale,1,,,,,
menu,1,,,,,
autoimport,0,,,,,
```

**Comment by jesusitd** [comment]
**LEAD TESTING SET UP DRAFT**

- [ ]  Add the `ITD Test Lead` field to all the active flows
- [ ]  Add Source mappings for: `ITD Test Lead` = `true` if (First, Last, Phone, Email) = `Official Test Lead Data`
- [ ]  Add a step criteria to `Intake Desk - Suppression List (GET)` step: `ITD Test Lead` **`is not true`**
- [ ]  Intake Desk Suppression List: `ITD Test Lead` **`is not true`**
- [ ]  SuppressionList 1-5: `ITD Test Lead` **`is not true`**
- [ ]  Ekata: `ITD Test Lead` **`is not true`**
- [ ]  DNC.com: `ITD Test Lead` **`is not true`**
- [ ]  Aanura: `ITD Test Lead` **`is not true`**
- [ ]  TeleSign: `ITD Test Lead` **`is not true`**
- [ ]  BriteVerify: `ITD Test Lead` **`is not true`**

**Flows checklist:**
- [x] Zantac - Vendors (test lead: https://next.leadconduit.com/events/5f57fa214a27426d5b3e50d1)
- [ ] Hernia Mesh - New Nick
- [ ] Talcum Powder - New Nick
- [ ] Roundup 2 - Vendors

**Other Tasks:**
- [ ] Document whole solution
- [ ] Set up new Operational Procedure for posting Test Leads (distribution to PIDs, Lead Posting Instructions update)

**Comment by jesusitd** [comment]
**Hit a roadblock:**
No Source mapping-level Rules are allowed: https://support.activeprospect.com/hc/en-us/articles/209564466-LeadConduit-Inbound-Field-Mapping

> Important Note: Rules do not function with Source mappings. Even though they appear to be available, rules in Source mappings can't access or evaluate any field values. Any Source mappings with rules will never execute.

This is a problem because we need to set the `ITD Test Lead` field to true if the data matches the Official Test Lead.

**Reaching out to LeadConduit Support.**

Alternative: create a recipient step that hits an internal API with either Power Automate or Azure API Management???? (Idk how to do it with the latter).

**Comment by jesusitd** [comment]
Solution proposal:
1. Created a small, non-authenticated API in Power Automate to validate test leads https://us.flow.microsoft.com/manage/environments/Default-011d0e09-4e96-4356-a27f-398562aca580/flows/69f90a7d-1a6f-48a5-8cb7-1af9f0dbb0b9/details
2. Added a custom Step on Zantac Vendors flow to hit the API: 
![image](https://user-images.githubusercontent.com/50643267/92799870-27f6b880-f382-11ea-96c1-0ec9284e13cc.png)
![image](https://user-images.githubusercontent.com/50643267/92799904-2fb65d00-f382-11ea-9f19-445c731609c4.png)
3. Used the field `TestLeadValidation.IsTestLead` from the API response to SKIP the appropriate steps
4. Set `test=1` in FORM POST if the custom field is true.

Tested successfully:
![image](https://user-images.githubusercontent.com/50643267/92800142-68563680-f382-11ea-9b16-d9dfd3597997.png)
![image](https://user-images.githubusercontent.com/50643267/92800267-8754c880-f382-11ea-9b05-896e4edbbf72.png)

**Comment by jesusitd** [comment]
@fedegarza let me know your thoughts, thanks!

**Comment by jesusitd** [comment]
**Latest update from LeadConduit support**:

> There would be a charge, and I haven't gotten a response back. So in the mean time I tried something else and think I have a work around. I created a test flow that you can look into. What I changed is in your first Suppression list step. I put in rules that said if first name = tester, last = intake etc. Then do not run the suppression list. What this does is we can later in rules state if suppression list is skipped, then skip this step as well. In short rather than creating a field for test, we know that if it skips the first suppression list step then its a test lead.

I just implemented this solution in "Zantac - Vendors" and looks correct after testing. Waiting some more feedback from LC, but this solution is better because it does not use any custom APIs, runs faster and cheaper.

Also, this is a Test Lead Posting Instructions draft for providers:
[Test Leads Posting Instruction.docx](https://github.com/intakedesk/PowerBI-General/files/5219744/Test.Leads.Posting.Instruction.docx)

**Comment by jesusitd** [comment]
After thinking, I believe this can be a solution:

1. Do not use the API to mark test leads. This is inefficient.
2. Only use a test lead email for this: **testlead@intakedesk.com**. Easy to remember, no risk of undesired collisions.
3. Set the step "Intake Desk Suppression List" to only trigger IF email NOT EQUAL to TEST EMAIL 
![image](https://user-images.githubusercontent.com/50643267/110340389-32270600-7ff7-11eb-9aa4-7284f7e1d5c2.png)
4. (All the SuppressionList steps below will not trigger either because they are set to skip if the Intake Desk Suppression List skips)
5. Configure the FORM POST step to Mark **test=1** IF email NOT EQUAL to TEST EMAIL.
![image](https://user-images.githubusercontent.com/50643267/110340267-128fdd80-7ff7-11eb-8009-07630044080e.png)
![image](https://user-images.githubusercontent.com/50643267/110342098-07d64800-7ff9-11eb-803e-c1458a2c1d51.png)

This is deployed in https://next.leadconduit.com/flows/60463d4f80673506c7c11e4c/edit/steps. Let's discuss it when possible @fedegarza

**Comment by fedegarza** [comment]
Approved

**Comment by jesusitd** [comment]
FLOWS Configured for this:

HERNIA MESH
ZANTAC
ROUNDUP 2 - Vendors
