### ISSUE TITLE
Define and Install on Power BI, New Set of Lead Statuses for Bogus Leads

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#61]
@nmusco Please send me the documentation of the Lead Status and Disposition Flow for Bogus Leads, so I can take action on the Power BI side to redefine applicable model issues.

Also, let's explore the possibility of sweeping Bogus Leads of last 2 weeks to mark them appropriately with UPDATE statements if applicable.

**Comment by nmusco** [comment]
Lead Statuses:
 - suspect_hold - The lead is suspected of being fraud and is awaiting review
 - fake_lead - The lead has been reviewed and has been determined to be fraudulent

Additional Fields:
 - suspect - This field will have one of the following values
    - -1 - The lead was suspected of being fraud, has been reviewed, and has been determined to be fraud
    - 0 - The lead is not suspected of being fraud
    - 1 - The lead is suspected of being fraud, and is awaiting review
    - 2 - The lead was suspected fo being fraud, has been reviewed, and has been determined to not be fraud.

**Comment by jesusitd** [comment]
@nmusco One question:

After the Lead is accepted if it was a suspect, is the `Lead Status` changed to `New_Dial`? or another one? and then moved to the dialer?

This way I can know if I have to explicitly ignore both `suspect_hold` and `fake_lead` statuses from all financial calculations.

**Comment by nmusco** [comment]
It is technically changed back to "New". Then when a separate scripts uploads it to the dialer that script changes the status to "New_Dial" (See intakedesk/crm.intakedesk.com#489 and the associated pull intakedesk/crm.intakedesk.com#493 - specifically https://github.com/intakedesk/crm.intakedesk.com/pull/493/files#diff-c02c9f8f50d81735d2ea8ccdafffd939R63).

**Comment by jesusitd** [comment]
Done.
