### ISSUE TITLE
Update and centralize documentation of all the department in SharePoint

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#619]

**Comment by CesarITD** [comment]
Points that are pending for documentation:
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\- Audiences and Hashes
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\- Data Sweeps
- **(Jesus will check it)** https://github.com/intakedesk/cdata-sync-facebook
- **(Jesus will check it)** https://intakedesk.sharepoint.com/sites/power-bi-docs/SitePages/LeadConduit-Sync.aspx
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\- Documents\PID Posting Instructions
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\- External Supp Lists
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\_powerautomate
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\PBI_Import
- \Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\Python Scripts
- How Tos (internal processes):

**Comment by CesarITD** [comment]
These was done the document, pending to put in the sharepoint page.
\Intakedesk LLC\Power BI Documentation - Power BI Desktop Files- Audiences and Hashes
\Intakedesk LLC\Power BI Documentation - Power BI Desktop Files- Data Sweeps

**Comment by jesusitd** [comment]
We might need to bring someone in specifically for this. Don't get me wrong but this needs dedication and perhaps someone of the documentation folks in the company can help us with this in a "documentation campaign" for a few weeks. @CesarITD @fedegarza

**Comment by jesusitd** [comment]
To close and open in new task upon requirement.
