### ISSUE TITLE
Add AWKO Hernia Mesh External List to Duplicates Cases solutions

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#633]

**Comment by CesarITD** [comment]
Added.

Done: 
- SQL Statements poor performance. SQL Insert Bridge.
- SQL Statements poor performance.  Master Supp List Table.

Pending:
- To put the Procedure in schedule.

**Comment by jesusitd** [comment]
Procedure **`master_suppression_lists`** was set to run with Refreshes Server in Python.

**Comment by jesusitd** [comment]
`Duplicate Leads and Cases` report now has this list working as expected.
![image](https://user-images.githubusercontent.com/50643267/97504738-dca66280-194d-11eb-93c6-c17e47947886.png)

Done.
