### ISSUE TITLE
Ad Spend and Converted by Hour Report

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#634]

**Comment by CesarITD** [comment]
- [x] Create new CDataSync integration to New Table (new granularity). facebook_sync.AdInsights_Ad_Hourly
- [x] To put new dataset in Power BI. Test with PID 3000.
- [x] To create a new draft report using base LEADS POSTED BY HOUR from Performance Report.
- [x] [Jesus] Load maybe 3 months of data, now we have only 7 days (09/25 to 10/01)
- [ ] Email to HK to evaluate solution in 3000.
- [ ] Clone to other Providers.
- [ ] Clone to 2.0.

**Comment by jesusitd** [comment]
Hi @CesarITD please help me updating this tomorrow, I think this is very close to be finished. Thanks!

**Comment by jesusitd** [comment]
Not looked into anymore.
