### ISSUE TITLE
Move Python Refresher account to new login from Ray

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#67]
I already succeeded at inviting bi_service@intakedesk.com as a member to `Clients Reports` and `Operations` workspaces.

Waiting on @nmusco to invite it to `Reports` workspace so I can now move on to replacing my personal company account with this service account for `pythonpowerbirefresher`.

**Comment by jesusitd** [comment]
Hi @nmusco Please provide `bi_service` account with the access requested above. Thanks!

**Comment by nmusco** [comment]
you need to request access from that account and then I can approve it.

**Comment by nmusco** [comment]
done

**Comment by jesusitd** [comment]
Moved credentials in Virtual Machine to `bi_service@intakedesk.com`.

Task Complete.
