### ISSUE TITLE
Run UPDATE Set SUBID_C for PID 6000 First Non-Test Leads

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#71]
Run an UPDATE query to set the correct Facebook AdId on the first leads sent by PID 6000, using the spreadsheet they sent us and matching it against what we already have in the CRM.

**Comment by jesusitd** [comment]
The list of Leads to update was grabbed using the following SELECT:
```sql
SELECT
    l.id AS lead_id
    , l.date_entered
    , p.name AS product
    , FIRST_name
    , LAST_name
    , subid_c
FROM
    leads l
LEFT JOIN leads_cstm lc ON
    l.id = lc.id_c
JOIN aos_products p ON
    l.lead_form_product_id = p.id
WHERE
    pid_c = '6000'
    AND NOT (
        first_name LIKE '%test%' OR last_name LIKE '%test%' OR first_name = '' OR last_name = ''
    )
    AND LEFT(subid_c, 1) <> '2'
ORDER BY
    l.date_entered DESC;
```
Resulting list is:
5da05bad-5c86-2a27-cd55-5d0ab55f5062	2019-06-19 22:23:36	IVC Filter Leads	**Michelle	Maxwell**	B2-001
297d8eca-dad7-2785-149f-5d0aaac13ee1	2019-06-19 21:34:16	Roundup Leads	**Elaine	Wolf**	RU-INTEREST-IMG2
401208e5-f0eb-b5eb-bcf2-5d0a98390e22	2019-06-19 20:16:32	Roundup Leads	**Marly	Jenks**	RU-INTEREST-IMG2
10397040-85e3-5cbe-68e1-5d0a7de74636	2019-06-19 18:22:10	IVC Filter Leads	**Nancy S.	Swanson**	A3-004
9b468f7d-6430-6a22-4020-5d0a5c941278	2019-06-19 16:00:17	IVC Filter Leads	**Typree	Lee**	C2-005
50b8c9bd-93ad-f40c-91d0-5d0a572fecac	2019-06-19 15:40:28	IVC Filter Leads	**Marcella	Dawson**	A2-004

**Comment by jesusitd** [comment]
Match against the spreadsheet sent by PID 6000:
[Intake Desk - June Leads.xlsx](https://github.com/intakedesk/PowerBI-General/files/3316968/Intake.Desk.-.June.Leads.xlsx)

**Comment by jesusitd** [comment]
Thus, the SQL UPDATE statements to run are:
```sql
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843371004860514' WHERE suitecrm.leads_cstm.id_c = '5da05bad-5c86-2a27-cd55-5d0ab55f5062';
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843371004980514' WHERE suitecrm.leads_cstm.id_c = '10397040-85e3-5cbe-68e1-5d0a7de74636';
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843371005040514' WHERE suitecrm.leads_cstm.id_c = '9b468f7d-6430-6a22-4020-5d0a5c941278';
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843371002240514' WHERE suitecrm.leads_cstm.id_c = '50b8c9bd-93ad-f40c-91d0-5d0a572fecac';
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843492992580268' WHERE suitecrm.leads_cstm.id_c = '297d8eca-dad7-2785-149f-5d0aaac13ee1';
UPDATE suitecrm.leads_cstm SET suitecrm.leads_cstm.subid_c = '23843492992580268' WHERE suitecrm.leads_cstm.id_c = '401208e5-f0eb-b5eb-bcf2-5d0a98390e22';
```
@nmusco Please assist us updating these leads

**Comment by jesusitd** [comment]
Hi @nmusco , please check if this one is complete thanks!

**Comment by nmusco** [comment]
this is complete.
