### ISSUE TITLE
PIDs: Develop AdsThumbnailsBinaries dimension to be able to sort Ads by Thumbnail

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#75]
Attempt to convert (and store) image binary data as PNG Base64 Encoded using procedure in:
https://www.blue-granite.com/blog/simple-steps-to-embed-images-in-power-bi
https://sqljason.com/2018/01/embedding-images-in-power-bi-using-base64.html

Power Query function that seems to work:
`Binary.ToText(Web.Contents([ThumbnailUrl]), BinaryEncoding.Base64)`

Tests being performed in PID 3000 report but loading is taking just too long.

**Comment by jesusitd** [comment]
Might need a server or serverless code ( :-) ) to run and grab the Base64 pics and keep them in the database.

That's also considering there might variate too!!!!!

**Comment by jesusitd** [comment]
Updated formula to:
`= Table.AddColumn(#"Removed Columns", "ThumbnailEncoded", each "data:image/png;base64," & Binary.ToText(Web.Contents([ThumbnailUrl]), BinaryEncoding.Base64), type text)`
and now allows to sort because it matches the images that are the same even if they have different URLs.

**PARTIAL SUCCESS**

Now need to figure out how to download the binaries without killing the dataset refresh.

Test with 6000 aggregating by thumbnail:
![image](https://user-images.githubusercontent.com/50643267/61488031-3d867300-a975-11e9-8205-2d4dc1ca40db.png)

**Comment by jesusitd** [comment]
Sent @nmusco an email seeking for help. Maybe storing the thumbnails in a separate table of facebook database will be good.

**Comment by jesusitd** [comment]
With this query I can grab the distinct `ImageHash` for that one PID, by specifying the `AdAccounts`, and gets the `MIN(ThumbnailUrl)`:
```sql
SELECT
    ImageHash
    , MIN(ThumbnailUrl) AS 'ThumbnailUrlRaw'
FROM
    Ads
LEFT JOIN AdCreatives ON
    Ads.AdCreativeId = AdCreatives.ID
INNER JOIN Campaigns ON
    Ads.CampaignId = Campaigns.ID AND Campaigns.Target IN (
    'act_1984773571634680',
    'act_309217666658076',
    'act_2188263681297029',
    'act_444783466101430'
    )
WHERE
    ThumbnailUrl IS NOT NULL
    AND ImageHash IS NOT NULL
GROUP BY
    ImageHash
```
and then I can quickly download the Base64 with Power Query:
```
let
    Source = MySQL.Database("slave1.sql.intakedesk.com", "facebook", [ReturnSingleDatabase=true, OldGuids=true, Query="SELECT..."]),
    #"Added Thumbnail Base64" = Table.AddColumn(Source, "ThumbnailUrl", each "data:image/png;base64," & Binary.ToText(Web.Contents([ThumbnailUrlRaw]), BinaryEncoding.Base64), type text)
in
    #"Added Thumbnail Base64"
```

Then I can LEFT JOIN this against `StageAdCreatives`

**Comment by jesusitd** [comment]
CREATED TEST TAB `TREND THUMBNAILS` on PID 6000 Report.

Show to HK.

**Comment by nmusco** [comment]
SELECT DISTINCT

    ImageHash,

    ThumbnailUrl AS 'ThumbnailUrlRaw'

FROM

    Ads

LEFT JOIN AdCreatives ON

    Ads.AdCreativeId = AdCreatives.ID

INNER JOIN Campaigns ON

    Ads.CampaignId = Campaigns.ID AND Campaigns.Target IN (

    'act_1984773571634680',

    'act_309217666658076',

    'act_2188263681297029',

    'act_444783466101430'

    )

WHERE

    ThumbnailUrl IS NOT NULL

    AND ImageHash IS NOT NULL

**Comment by jesusitd** [comment]
CC @CesarITD let's use hash to get Image IDS

**Comment by jesusitd** [comment]
Requirement Outdated.
